/*
 Xinghe Xunjing module schema for MySQL.
 Apply after sql/mysql/ruoyi-vue-pro.sql in a standalone Xinghe Xunjing database.
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `xunjing_project` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '项目编号',
  `code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '项目编码',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '项目名称',
  `region_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '区域名称',
  `phase` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '项目阶段',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xunjing_project_code_tenant` (`code`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境项目';

CREATE TABLE IF NOT EXISTS `xunjing_school` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '学校编号',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '学校名称',
  `region_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '区域名称',
  `contact_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '联系电话',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_school_region` (`region_name`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境学校';

CREATE TABLE IF NOT EXISTS `xunjing_resource_package` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '资源包编号',
  `project_id` bigint NOT NULL COMMENT '项目编号',
  `school_id` bigint NOT NULL COMMENT '学校编号',
  `package_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '资源包编码',
  `title` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `resource_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '资源类型',
  `version_no` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '版本号',
  `ai_knowledge_id` bigint DEFAULT NULL COMMENT 'Yudao AI 知识库编号',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `published_at` datetime DEFAULT NULL COMMENT '发布时间',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xunjing_package_code_tenant` (`package_code`, `tenant_id`),
  KEY `idx_xunjing_package_project` (`project_id`, `tenant_id`),
  KEY `idx_xunjing_package_school` (`school_id`, `tenant_id`),
  KEY `idx_xunjing_package_ai_knowledge` (`ai_knowledge_id`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境实体资源包';

CREATE TABLE IF NOT EXISTS `xunjing_knowledge_document` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '知识文档编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `title` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `source_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '来源类型',
  `source_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源链接',
  `content_digest` text COLLATE utf8mb4_unicode_ci COMMENT '内容摘要',
  `authority_level` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '权威等级',
  `review_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '审核状态',
  `vector_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '向量状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_doc_package` (`package_id`, `tenant_id`),
  KEY `idx_xunjing_doc_review_vector` (`review_status`, `vector_status`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境知识库文档';

CREATE TABLE IF NOT EXISTS `xunjing_media_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '素材编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `title` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `media_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '素材类型',
  `file_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件地址',
  `object_key` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '对象存储 Key',
  `source_provider` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源机构',
  `source_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源链接',
  `copyright_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '版权状态',
  `review_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '审核状态',
  `image_tags` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图片标签 JSON',
  `can_public` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否可公开展示',
  `can_ai_use` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否可用于 AI',
  `can_promotion_use` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否可用于宣传',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_media_package` (`package_id`, `tenant_id`),
  KEY `idx_xunjing_media_review` (`review_status`, `copyright_status`, `can_public`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境图片/视频/模型素材';

CREATE TABLE IF NOT EXISTS `xunjing_media_usage_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '素材调用编号',
  `media_id` bigint NOT NULL COMMENT '素材编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `scene_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '调用场景',
  `usage_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '调用类型',
  `caller` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '调用方',
  `payload_json` text COLLATE utf8mb4_unicode_ci COMMENT '调用载荷 JSON',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_media_usage_media` (`media_id`, `tenant_id`),
  KEY `idx_xunjing_media_usage_package` (`package_id`, `tenant_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境素材调用日志';

CREATE TABLE IF NOT EXISTS `xunjing_map_point` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '地图点位编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `title` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
  `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',
  `summary` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '摘要',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_map_package` (`package_id`, `tenant_id`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境地图点位';

CREATE TABLE IF NOT EXISTS `xunjing_globe_model` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '地球仪模型编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `title` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `model_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '模型地址',
  `cover_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '封面地址',
  `data_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '数据版本',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_globe_package` (`package_id`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境地球仪模型';

CREATE TABLE IF NOT EXISTS `xunjing_interaction_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '事件编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `school_id` bigint DEFAULT NULL COMMENT '学校编号',
  `event_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '事件类型',
  `source_channel` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源渠道',
  `user_trace_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '匿名用户追踪编号',
  `payload_json` text COLLATE utf8mb4_unicode_ci COMMENT '事件载荷 JSON',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_event_package` (`package_id`, `tenant_id`, `create_time`),
  KEY `idx_xunjing_event_school` (`school_id`, `tenant_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境访问事件';

CREATE TABLE IF NOT EXISTS `xunjing_qrcode` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '二维码编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '二维码名称',
  `scene_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '场景码',
  `path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '小程序路径',
  `target_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '目标类型',
  `target_id` bigint NOT NULL COMMENT '目标编号',
  `scan_count` bigint NOT NULL DEFAULT 0 COMMENT '扫码次数',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xunjing_qrcode_scene_tenant` (`scene_code`, `tenant_id`),
  KEY `idx_xunjing_qrcode_package` (`package_id`, `tenant_id`),
  KEY `idx_xunjing_qrcode_target` (`target_type`, `target_id`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境二维码';

CREATE TABLE IF NOT EXISTS `xunjing_public_report` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '报告编号',
  `project_id` bigint NOT NULL COMMENT '项目编号',
  `school_id` bigint DEFAULT NULL COMMENT '学校编号',
  `title` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `report_period` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报告周期',
  `metrics_json` text COLLATE utf8mb4_unicode_ci COMMENT '指标 JSON',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `generated_at` datetime DEFAULT NULL COMMENT '生成时间',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_report_project` (`project_id`, `tenant_id`, `report_period`),
  KEY `idx_xunjing_report_school` (`school_id`, `tenant_id`, `report_period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境公益报告';

CREATE TABLE IF NOT EXISTS `xunjing_crawler_source` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '采集来源编号',
  `project_id` bigint NOT NULL COMMENT '项目编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `source_url` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '来源 URL',
  `host` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源域名',
  `source_kind` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '来源类型',
  `connector` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '采集连接器',
  `source_lane` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '来源通道',
  `capture_profile` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '采集配置',
  `fact_source_policy` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '事实来源策略',
  `capture_assets` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否采集素材',
  `metadata_only` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否仅采元数据',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `blocked_reason_hint` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '阻断原因提示',
  `notes` text COLLATE utf8mb4_unicode_ci COMMENT '备注',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_crawler_project` (`project_id`, `tenant_id`),
  KEY `idx_xunjing_crawler_package` (`package_id`, `tenant_id`),
  KEY `idx_xunjing_crawler_host` (`host`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境资料导入采集来源';

CREATE TABLE IF NOT EXISTS `xunjing_import_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '导入项编号',
  `source_id` bigint DEFAULT NULL COMMENT '采集来源编号',
  `project_id` bigint NOT NULL COMMENT '项目编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `item_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '导入项类型',
  `item_title` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '导入项标题',
  `original_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原始 URL',
  `file_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件 URL',
  `source_provider` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源机构',
  `evidence_text` text COLLATE utf8mb4_unicode_ci COMMENT '授权和来源证据',
  `target_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标类型',
  `target_id` bigint DEFAULT NULL COMMENT '目标编号',
  `review_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '审核状态',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '导入状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_import_project` (`project_id`, `tenant_id`, `review_status`),
  KEY `idx_xunjing_import_package` (`package_id`, `tenant_id`),
  KEY `idx_xunjing_import_source` (`source_id`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境资料导入待审核项';

CREATE TABLE IF NOT EXISTS `xunjing_ai_eval_set` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'AI评测集编号',
  `project_id` bigint NOT NULL COMMENT '项目编号',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '评测集名称',
  `scene_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '场景编码',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_ai_eval_set_project` (`project_id`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境AI评测集';

CREATE TABLE IF NOT EXISTS `xunjing_ai_eval_case` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'AI评测问题编号',
  `eval_set_id` bigint NOT NULL COMMENT '评测集编号',
  `question` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '问题',
  `expected_policy` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '期望策略',
  `risk_tags` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '风险标签',
  `source_required` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否必须带来源',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_ai_eval_case_set` (`eval_set_id`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境AI评测问题';

CREATE TABLE IF NOT EXISTS `xunjing_ai_quota_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'AI配额规则编号',
  `project_id` bigint NOT NULL COMMENT '项目编号',
  `scope_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '作用域类型',
  `scope_id` bigint DEFAULT NULL COMMENT '作用域编号',
  `scene_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '场景编码',
  `daily_limit` int NOT NULL COMMENT '每日调用上限',
  `monthly_budget` decimal(18,6) DEFAULT NULL COMMENT '月预算',
  `cache_enabled` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否启用缓存',
  `fallback_model_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '降级模型',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_ai_quota_project` (`project_id`, `tenant_id`),
  KEY `idx_xunjing_ai_quota_scope` (`scope_type`, `scope_id`, `scene_code`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境AI调用配额规则';

CREATE TABLE IF NOT EXISTS `xunjing_ai_generation_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'AI调用日志编号',
  `project_id` bigint NOT NULL COMMENT '项目编号',
  `school_id` bigint DEFAULT NULL COMMENT '学校编号',
  `package_id` bigint NOT NULL COMMENT '资源包编号',
  `qr_code_id` bigint DEFAULT NULL COMMENT '二维码编号',
  `scene_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '场景编码',
  `user_trace_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '匿名用户追踪编号',
  `model_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模型编码',
  `prompt_version` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提示词版本',
  `input_summary` text COLLATE utf8mb4_unicode_ci COMMENT '输入摘要',
  `output_summary` text COLLATE utf8mb4_unicode_ci COMMENT '输出摘要',
  `source_json` text COLLATE utf8mb4_unicode_ci COMMENT '来源 JSON',
  `token_count` bigint NOT NULL DEFAULT 0 COMMENT 'Token 数',
  `cost_amount` decimal(18,6) NOT NULL DEFAULT 0 COMMENT '成本金额',
  `safety_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '安全状态',
  `cache_hit` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否命中缓存',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_xunjing_ai_log_project` (`project_id`, `tenant_id`, `create_time`),
  KEY `idx_xunjing_ai_log_school` (`school_id`, `tenant_id`, `create_time`),
  KEY `idx_xunjing_ai_log_qrcode` (`qr_code_id`, `tenant_id`, `create_time`),
  KEY `idx_xunjing_ai_log_user` (`user_trace_id`, `tenant_id`, `create_time`),
  KEY `idx_xunjing_ai_log_package` (`package_id`, `tenant_id`, `create_time`),
  KEY `idx_xunjing_ai_log_scene` (`scene_code`, `tenant_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='星河寻境AI调用成本日志';

INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES
(880000, '星河寻境', '', 1, 60, 0, '/xunjing', 'ep:location', NULL, NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880001, '星河寻境工作台', 'xunjing:resource-package:query', 2, 1, 880000, 'console', 'ep:map-location', 'xunjing/console/index', 'XunjingConsole', 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880101, '项目新增', 'xunjing:project:create', 3, 1, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880102, '学校新增', 'xunjing:school:create', 3, 2, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880103, '资源包新增', 'xunjing:resource-package:create', 3, 3, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880104, '资源包查询', 'xunjing:resource-package:query', 3, 4, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880105, '知识新增', 'xunjing:knowledge:create', 3, 5, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880106, '素材新增', 'xunjing:media:create', 3, 6, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880107, '地图点新增', 'xunjing:map-point:create', 3, 7, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880108, '地球仪新增', 'xunjing:globe-model:create', 3, 8, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880109, '事件回传', 'xunjing:event:create', 3, 9, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880110, '就绪度查询', 'xunjing:readiness:query', 3, 10, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880111, '公益报告生成', 'xunjing:public-report:create', 3, 11, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880112, '采集来源新增', 'xunjing:crawler-source:create', 3, 12, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880113, '采集来源查询', 'xunjing:crawler-source:query', 3, 13, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880114, '资料导入新增', 'xunjing:import-item:create', 3, 14, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880115, '资料导入查询', 'xunjing:import-item:query', 3, 15, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880116, '素材调用新增', 'xunjing:media-usage:create', 3, 16, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880117, '素材调用查询', 'xunjing:media-usage:query', 3, 17, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880118, 'AI评测新增', 'xunjing:ai-eval:create', 3, 18, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880119, 'AI评测查询', 'xunjing:ai-eval:query', 3, 19, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880120, 'AI配额新增', 'xunjing:ai-quota:create', 3, 20, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880121, 'AI配额查询', 'xunjing:ai-quota:query', 3, 21, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880122, 'AI日志新增', 'xunjing:ai-log:create', 3, 22, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880123, 'AI日志查询', 'xunjing:ai-log:query', 3, 23, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880124, '二维码新增', 'xunjing:qrcode:create', 3, 24, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880125, '二维码查询', 'xunjing:qrcode:query', 3, 25, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880126, '看板查询', 'xunjing:dashboard:query', 3, 26, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880127, '资料导入审核', 'xunjing:import-item:review', 3, 27, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880128, '资源包更新', 'xunjing:resource-package:update', 3, 28, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880129, '知识查询', 'xunjing:knowledge:query', 3, 29, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880130, '知识审核', 'xunjing:knowledge:review', 3, 30, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880131, '素材查询', 'xunjing:media:query', 3, 31, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880132, '素材审核', 'xunjing:media:review', 3, 32, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880133, '二维码更新', 'xunjing:qrcode:update', 3, 33, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880134, 'AI评测运行', 'xunjing:ai-eval:run', 3, 34, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880135, '采集来源运行', 'xunjing:crawler-source:run', 3, 35, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880136, '地图点查询', 'xunjing:map-point:query', 3, 36, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
(880137, '地球仪查询', 'xunjing:globe-model:query', 3, 37, 880001, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', NOW(), 'admin', NOW(), b'0')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `permission` = VALUES(`permission`),
  `type` = VALUES(`type`),
  `sort` = VALUES(`sort`),
  `parent_id` = VALUES(`parent_id`),
  `path` = VALUES(`path`),
  `icon` = VALUES(`icon`),
  `component` = VALUES(`component`),
  `component_name` = VALUES(`component_name`),
  `status` = VALUES(`status`),
  `visible` = VALUES(`visible`),
  `keep_alive` = VALUES(`keep_alive`),
  `always_show` = VALUES(`always_show`),
  `updater` = 'admin',
  `update_time` = NOW(),
  `deleted` = b'0';

SET FOREIGN_KEY_CHECKS = 1;
