/*
 Xinghe Xunjing Xicheng P0 local-candidate seed data.
 Apply after sql/mysql/xunjing-module.sql in a standalone Xinghe Xunjing database.
 This seed is for local/preflight APP integration. It includes public-source Xicheng candidate POIs; coordinates and source licenses remain REVIEW_REQUIRED before production.
*/

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 0;

SET @tenant_id := 1;
SET @xicheng_source_url := 'https://www.bjxch.gov.cn/xxgk/zdly/jgxx/lyscjg/Ajjyxlyjqml.html';
SET @xicheng_heritage_source_url := 'https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html';

INSERT INTO `xunjing_project`
(`code`, `name`, `region_name`, `phase`, `status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
('XICHENG-2026-P0', '星河寻境·西城 AI 旅伴真实试运营版', '北京西城', 'P0', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `region_name` = VALUES(`region_name`),
  `phase` = VALUES(`phase`),
  `status` = VALUES(`status`),
  `updater` = 'admin',
  `update_time` = NOW(),
  `deleted` = b'0';

SET @project_id := (
  SELECT `id` FROM `xunjing_project`
  WHERE `code` = 'XICHENG-2026-P0' AND `tenant_id` = @tenant_id
  LIMIT 1
);

INSERT INTO `xunjing_school`
(`name`, `region_name`, `contact_name`, `contact_phone`, `status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
SELECT '西城试运营项目组', '北京西城', '项目运营', '138****0000', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id
WHERE NOT EXISTS (
  SELECT 1 FROM `xunjing_school`
  WHERE `name` = '西城试运营项目组' AND `region_name` = '北京西城' AND `tenant_id` = @tenant_id
);

SET @school_id := (
  SELECT `id` FROM `xunjing_school`
  WHERE `name` = '西城试运营项目组' AND `region_name` = '北京西城' AND `tenant_id` = @tenant_id
  ORDER BY `id` DESC
  LIMIT 1
);

INSERT INTO `xunjing_resource_package`
(`project_id`, `school_id`, `package_code`, `title`, `resource_type`, `version_no`, `status`, `published_at`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
(@project_id, @school_id, 'XICHENG-MAP-001', '西城 AI 旅伴真实试运营地图', 'MAP', 'v0.1.0-local-candidate', 'PUBLISHED', NOW(), 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id)
ON DUPLICATE KEY UPDATE
  `project_id` = VALUES(`project_id`),
  `school_id` = VALUES(`school_id`),
  `title` = VALUES(`title`),
  `resource_type` = VALUES(`resource_type`),
  `version_no` = VALUES(`version_no`),
  `status` = VALUES(`status`),
  `published_at` = VALUES(`published_at`),
  `updater` = 'admin',
  `update_time` = NOW(),
  `deleted` = b'0';

SET @map_package_id := (
  SELECT `id` FROM `xunjing_resource_package`
  WHERE `package_code` = 'XICHENG-MAP-001' AND `tenant_id` = @tenant_id
  LIMIT 1
);

DELETE FROM `xunjing_knowledge_document`
WHERE `tenant_id` = @tenant_id
  AND `package_id` = @map_package_id
  AND (
    `source_url` COLLATE utf8mb4_unicode_ci IN (
      @xicheng_source_url COLLATE utf8mb4_unicode_ci,
      @xicheng_heritage_source_url COLLATE utf8mb4_unicode_ci,
      _utf8mb4'https://whlyj.beijing.gov.cn/' COLLATE utf8mb4_unicode_ci,
      _utf8mb4'internal://xunjing/xicheng/p0-trigger-policy' COLLATE utf8mb4_unicode_ci
    )
    OR `source_url` COLLATE utf8mb4_unicode_ci LIKE CONCAT(@xicheng_source_url, _utf8mb4'#%') COLLATE utf8mb4_unicode_ci
    OR `source_url` COLLATE utf8mb4_unicode_ci LIKE CONCAT(@xicheng_heritage_source_url, _utf8mb4'#%') COLLATE utf8mb4_unicode_ci
  );

DELETE FROM `xunjing_poi`
WHERE `tenant_id` = @tenant_id
  AND `package_id` = @map_package_id;

DELETE FROM `xunjing_map_point`
WHERE `tenant_id` = @tenant_id
  AND `package_id` = @map_package_id;

DELETE FROM `xunjing_qrcode`
WHERE `tenant_id` = @tenant_id
  AND `package_id` = @map_package_id;

DELETE FROM `xunjing_public_report`
WHERE `tenant_id` = @tenant_id
  AND `project_id` = @project_id
  AND `title` = '西城 P0 后台本地候选状态';

INSERT INTO `xunjing_knowledge_document`
(`package_id`, `title`, `source_type`, `source_url`, `content_digest`, `authority_level`, `review_status`, `vector_status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
(@map_package_id, '西城首批文旅 POI 公开来源索引', 'OFFICIAL_PUBLIC', @xicheng_source_url, '西城 P0 本地候选以 PRD 首期推荐 POI 池为范围，优先覆盖景区、公园、博物馆、名人故居、历史街区和游客服务点。生产发布前必须完成来源授权、坐标复核和内容审核。', 'OFFICIAL', 'APPROVED', 'INDEXED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, '西城区文物保护单位（81处）', 'OFFICIAL_PUBLIC', @xicheng_heritage_source_url, '西城区文化和旅游局公开发布的区级文物保护单位名单，提供名称、级别和地址。当前用于后台候选 POI 填充；生产发布前仍需坐标、现场识别和授权复核。', 'OFFICIAL', 'APPROVED', 'INDEXED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, '北京文旅公开信息辅助索引', 'OFFICIAL_PUBLIC', 'https://whlyj.beijing.gov.cn/', '用于辅助核验北京文旅公开信息。AI 回答只允许引用已审核知识文档，不得根据未复核实时开放、票价、活动或路线信息编造答案。', 'OFFICIAL', 'APPROVED', 'INDEXED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, '西城多模态触发上线策略', 'MANUAL', 'internal://xunjing/xicheng/p0-trigger-policy', '扫一扫、OCR、照片识别、定位和文本输入统一进入多模态触发引擎。无来源或未审核内容必须返回 BLOCKED 或请求人工确认。坐标和地图路线在生产前必须完成授权和现场复核。', 'EDITORIAL', 'APPROVED', 'INDEXED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id);

INSERT INTO `xunjing_poi`
(`package_id`, `poi_code`, `region_code`, `name`, `official_name`, `aliases_json`, `category`, `poi_level`, `address`, `latitude`, `longitude`, `coord_type`, `source_json`, `trigger_json`, `content_json`, `review_status`, `geo_status`, `license_status`, `status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
(@map_package_id, 'xicheng-baitasi', 'beijing-xicheng', '妙应寺白塔', '妙应寺白塔', '["妙应寺白塔","妙应寺","白塔寺","白塔寺东夹道","白塔"]', 'heritage_site', 'P0', '北京市西城区阜成门内大街171号', 39.9231000, 116.3572600, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":220,"ocrKeywords":["白塔寺","妙应寺","妙应寺白塔","白塔"],"photoLabels":["white_pagoda","pagoda","temple","miaoying_temple"],"minConfidence":0.85}', '{"poiId":"xicheng-baitasi","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"西城白塔寺片区的历史文化地标。","recommendedQuestions":["白塔寺为什么重要？","白塔寺片区适合怎么 Citywalk？","这里有什么适合拍照的点？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-emperors-temple', 'beijing-xicheng', '历代帝王庙', '北京历代帝王庙', '["历代帝王庙","帝王庙","帝王庙大街"]', 'heritage_site', 'P0', '北京市西城区阜成门内大街131号', 39.9189300, 116.3658700, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["历代帝王庙","帝王庙"],"photoLabels":["imperial_temple","temple","paifang","beijing_architecture"],"minConfidence":0.85}', '{"poiId":"xicheng-emperors-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"理解北京礼制文化和老城街区的重要点位。","recommendedQuestions":["历代帝王庙为什么重要？","从这里下一站推荐去哪？","适合亲子研学怎么讲？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-beihai-park', 'beijing-xicheng', '北海公园', '北海公园', '["北海公园","北海","琼华岛","北海白塔"]', 'park_scenic', 'P0', '北京市西城区文津街1号', 39.9254500, 116.3890200, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":520,"ocrKeywords":["北海公园","北海","琼华岛","北海白塔"],"photoLabels":["lake","imperial_garden","white_tower","park"],"minConfidence":0.85}', '{"poiId":"xicheng-beihai-park","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"皇家园林、白塔和水岸空间共同构成的北京文化地标。","recommendedQuestions":["北海公园有哪些必看点？","北海白塔和妙应寺白塔有什么区别？","适合半日游怎么走？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-shichahai', 'beijing-xicheng', '什刹海', '什刹海', '["什刹海","后海","前海","西海","烟袋斜街"]', 'historic_district', 'P0', '北京市西城区什刹海片区', 39.9403100, 116.3863900, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":650,"ocrKeywords":["什刹海","后海","前海","西海"],"photoLabels":["lake","hutong","waterfront","old_beijing"],"minConfidence":0.85}', '{"poiId":"xicheng-shichahai","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"胡同、水系和市井生活交织的老北京漫游片区。","recommendedQuestions":["什刹海适合怎么逛？","这里有哪些老北京故事？","附近下一站推荐哪里？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-dashilar', 'beijing-xicheng', '大栅栏', '大栅栏', '["大栅栏","前门大栅栏","杨梅竹斜街","北京坊"]', 'historic_commerce', 'P0', '北京市西城区大栅栏片区', 39.8943800, 116.3936600, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":360,"ocrKeywords":["大栅栏","前门大栅栏","杨梅竹斜街","北京坊"],"photoLabels":["hutong","shop_sign","old_beijing","dashilar"],"minConfidence":0.85}', '{"poiId":"xicheng-dashilar","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"老字号、商业街巷和近代城市生活的西城代表片区。","recommendedQuestions":["大栅栏有哪些老字号？","这条街适合怎么拍照？","附近适合亲子观察什么？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-gongwangfu', 'beijing-xicheng', '恭王府', '恭王府博物馆', '["恭王府","恭王府博物馆","和珅府"]', 'museum_scenic', 'P0', '北京市西城区前海西街17号', 39.9370500, 116.3867700, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":280,"ocrKeywords":["恭王府","恭王府博物馆"],"photoLabels":["palace","garden","courtyard","museum"],"minConfidence":0.85}', '{"poiId":"xicheng-gongwangfu","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"西城王府文化和园林空间的代表性点位。","recommendedQuestions":["恭王府适合怎么参观？","王府文化怎么给孩子讲？","附近还能去哪？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-jingshan-park', 'beijing-xicheng', '景山公园', '景山公园', '["景山公园","景山","万春亭"]', 'park_scenic', 'P0', '北京市景山前街44号', 39.9253200, 116.3971000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":420,"ocrKeywords":["景山公园","景山","万春亭"],"photoLabels":["park","hill","imperial_city"],"minConfidence":0.85}', '{"poiId":"xicheng-jingshan-park","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"观察北京老城格局和中轴空间的重要公园。","recommendedQuestions":["景山为什么适合看北京城？","这里和中轴线有什么关系？","怎么安排半日路线？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-beijing-zoo', 'beijing-xicheng', '北京动物园', '北京动物园', '["北京动物园","动物园","熊猫馆"]', 'family_scenic', 'P0', '北京市西城区西直门外大街137号', 39.9387500, 116.3424200, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":520,"ocrKeywords":["北京动物园","动物园","熊猫馆"],"photoLabels":["zoo","animal","panda","family"],"minConfidence":0.85}', '{"poiId":"xicheng-beijing-zoo","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"亲子研学和城市公共文化游览的高频点位。","recommendedQuestions":["北京动物园适合怎样亲子游？","可以观察哪些动物行为？","附近怎么接北京天文馆？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-planetarium', 'beijing-xicheng', '北京天文馆', '北京天文馆', '["北京天文馆","天文馆","天象厅"]', 'science_museum', 'P0', '北京市西城区西直门外大街138号', 39.9388000, 116.3439800, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":260,"ocrKeywords":["北京天文馆","天文馆","天象厅"],"photoLabels":["planetarium","science","dome","museum"],"minConfidence":0.85}', '{"poiId":"xicheng-planetarium","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"适合把城市旅行和天文科学体验连接起来的科普场馆。","recommendedQuestions":["天文馆适合孩子怎么看？","有哪些适合拍照的展项？","和动物园怎么串联？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-daguanyuan', 'beijing-xicheng', '北京大观园', '北京大观园', '["北京大观园","大观园","红楼梦大观园"]', 'culture_park', 'P0', '北京市西城区南菜园西街12号', 39.8693600, 116.3568400, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":380,"ocrKeywords":["北京大观园","大观园","红楼梦"],"photoLabels":["garden","classic_literature","pavilion"],"minConfidence":0.85}', '{"poiId":"xicheng-daguanyuan","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"连接文学、园林和影视记忆的文化游览点位。","recommendedQuestions":["大观园和红楼梦有什么关系？","这里适合怎么讲给孩子？","有哪些路线可以串联？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-xuanwu-park', 'beijing-xicheng', '宣武艺园', '宣武艺园', '["宣武艺园","宣武公园","艺园"]', 'park_scenic', 'P0', '北京市西城区槐柏树街12号', 39.8906000, 116.3626000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":280,"ocrKeywords":["宣武艺园","宣武公园","艺园"],"photoLabels":["park","garden","community"],"minConfidence":0.85}', '{"poiId":"xicheng-xuanwu-park","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"适合观察西城社区公园和城市公共空间。","recommendedQuestions":["宣武艺园适合怎么休闲？","附近有哪些文化点？","亲子观察可以看什么？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-jinzhongdu-park', 'beijing-xicheng', '金中都公园', '金中都公园', '["金中都公园","金中都","中都遗址"]', 'heritage_park', 'P0', '北京市西城区广安门南滨河路', 39.8637000, 116.3498600, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":320,"ocrKeywords":["金中都公园","金中都","中都遗址"],"photoLabels":["park","heritage","city_wall"],"minConfidence":0.85}', '{"poiId":"xicheng-jinzhongdu-park","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"帮助理解北京城市历史层叠关系的遗址公园。","recommendedQuestions":["金中都和北京城有什么关系？","这里适合讲什么历史？","附近怎么安排路线？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-geology-museum', 'beijing-xicheng', '中国地质博物馆', '中国地质博物馆', '["中国地质博物馆","地质博物馆","地博"]', 'museum', 'P0', '北京市西城区西四羊肉胡同15号', 39.9233500, 116.3682100, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":220,"ocrKeywords":["中国地质博物馆","地质博物馆","地博"],"photoLabels":["museum","geology","science","fossil"],"minConfidence":0.85}', '{"poiId":"xicheng-geology-museum","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"适合连接自然科学、地球知识和城市研学的博物馆。","recommendedQuestions":["地质博物馆适合看什么？","怎么给孩子讲矿物和化石？","附近还有哪些文化点？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-xuannan-museum', 'beijing-xicheng', '宣南文化博物馆', '宣南文化博物馆', '["宣南文化博物馆","宣南文化","长椿寺"]', 'museum', 'P0', '北京市西城区长椿街9号', 39.8871800, 116.3740000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":220,"ocrKeywords":["宣南文化博物馆","宣南文化","长椿寺"],"photoLabels":["museum","temple","culture"],"minConfidence":0.85}', '{"poiId":"xicheng-xuannan-museum","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"理解宣南文化和北京南城文脉的重要窗口。","recommendedQuestions":["什么是宣南文化？","这里适合怎么参观？","附近能串联哪些点？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-songqingling', 'beijing-xicheng', '宋庆龄故居', '中华人民共和国名誉主席宋庆龄同志故居', '["宋庆龄故居","宋庆龄同志故居","后海北沿"]', 'former_residence', 'P0', '北京市西城区后海北沿46号', 39.9443500, 116.3829300, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":220,"ocrKeywords":["宋庆龄故居","宋庆龄同志故居"],"photoLabels":["former_residence","courtyard","garden"],"minConfidence":0.85}', '{"poiId":"xicheng-songqingling","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"什刹海片区重要名人故居和爱国主义教育点位。","recommendedQuestions":["宋庆龄故居适合怎么讲？","这里和什刹海有什么关系？","亲子研学关注什么？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-guomoruo', 'beijing-xicheng', '郭沫若纪念馆', '郭沫若纪念馆', '["郭沫若纪念馆","郭沫若故居","前海西街"]', 'former_residence', 'P0', '北京市西城区前海西街18号', 39.9396000, 116.3846200, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":200,"ocrKeywords":["郭沫若纪念馆","郭沫若故居","郭沫若"],"photoLabels":["former_residence","courtyard","writer"],"minConfidence":0.85}', '{"poiId":"xicheng-guomoruo","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"什刹海周边名人故居文化线路的重要节点。","recommendedQuestions":["郭沫若纪念馆适合看什么？","这里可以怎么和恭王府串联？","适合讲哪些文学主题？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-luxun-museum', 'beijing-xicheng', '鲁迅博物馆', '北京鲁迅博物馆', '["鲁迅博物馆","北京鲁迅博物馆","鲁迅故居"]', 'museum', 'P0', '北京市西城区阜成门内宫门口二条19号', 39.9234700, 116.3560000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":220,"ocrKeywords":["鲁迅博物馆","北京鲁迅博物馆","鲁迅故居"],"photoLabels":["museum","writer","former_residence"],"minConfidence":0.85}', '{"poiId":"xicheng-luxun-museum","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"连接现代文学、名人故居和白塔寺片区路线的文化点位。","recommendedQuestions":["鲁迅博物馆适合怎么参观？","这里和白塔寺片区怎么串联？","适合孩子理解哪些主题？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-huguang-guild-hall', 'beijing-xicheng', '湖广会馆大戏楼', '湖广会馆大戏楼', '["湖广会馆","湖广会馆大戏楼","大戏楼"]', 'theater_culture', 'P0', '北京市西城区虎坊路3号', 39.8934500, 116.3772500, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":220,"ocrKeywords":["湖广会馆","湖广会馆大戏楼","大戏楼"],"photoLabels":["theater","guild_hall","opera_stage"],"minConfidence":0.85}', '{"poiId":"xicheng-huguang-guild-hall","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"会馆文化和戏曲空间的代表性点位。","recommendedQuestions":["湖广会馆为什么重要？","大戏楼适合怎么看？","附近可以怎么 Citywalk？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-laoshe-teahouse', 'beijing-xicheng', '老舍茶馆', '老舍茶馆', '["老舍茶馆","茶馆","前门茶馆"]', 'culture_space', 'P0', '北京市西城区前门西大街正阳市场3号楼', 39.8994500, 116.3917000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["老舍茶馆","茶馆","前门茶馆"],"photoLabels":["teahouse","stage","old_beijing"],"minConfidence":0.85}', '{"poiId":"xicheng-laoshe-teahouse","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"展示北京茶馆、曲艺和游客文化消费的代表空间。","recommendedQuestions":["老舍茶馆适合体验什么？","这里和前门大栅栏怎么串联？","有哪些北京文化元素？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-fuchengmennei-street', 'beijing-xicheng', '阜成门内大街', '阜成门内大街', '["阜成门内大街","阜内大街","阜成门"]', 'citywalk_street', 'P0', '北京市西城区阜成门内大街', 39.9230000, 116.3600000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":500,"ocrKeywords":["阜成门内大街","阜内大街","阜成门"],"photoLabels":["street","hutong","old_city"],"minConfidence":0.85}', '{"poiId":"xicheng-fuchengmennei-street","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"串联白塔寺、历代帝王庙和周边胡同的重要 Citywalk 街段。","recommendedQuestions":["阜成门内大街适合怎么走？","这条路能串联哪些点？","路上可以观察什么？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-yandai-xiejie', 'beijing-xicheng', '烟袋斜街', '烟袋斜街', '["烟袋斜街","烟袋","什刹海烟袋斜街"]', 'historic_street', 'P0', '北京市西城区烟袋斜街', 39.9407000, 116.3915500, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":220,"ocrKeywords":["烟袋斜街","烟袋"],"photoLabels":["hutong","shop_sign","historic_street"],"minConfidence":0.85}', '{"poiId":"xicheng-yandai-xiejie","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"什刹海胡同漫游线上的高频街巷点。","recommendedQuestions":["烟袋斜街为什么出名？","这里适合拍什么？","怎么接银锭桥和后海？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-yinding-bridge', 'beijing-xicheng', '银锭桥', '银锭桥', '["银锭桥","银锭观山","后海银锭桥"]', 'bridge_landmark', 'P0', '北京市西城区什刹海前海与后海之间', 39.9409000, 116.3878000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":160,"ocrKeywords":["银锭桥","银锭观山"],"photoLabels":["bridge","lake","waterfront"],"minConfidence":0.85}', '{"poiId":"xicheng-yinding-bridge","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"什刹海水系和胡同漫游的重要地标。","recommendedQuestions":["银锭桥有什么故事？","这里适合怎么看什刹海？","下一站推荐哪里？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-niujie', 'beijing-xicheng', '牛街', '牛街', '["牛街","牛街片区","牛街美食"]', 'historic_food_street', 'P0', '北京市西城区牛街', 39.8831600, 116.3601000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":420,"ocrKeywords":["牛街","牛街美食","牛街片区"],"photoLabels":["food_street","old_beijing","street"],"minConfidence":0.85}', '{"poiId":"xicheng-niujie","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"适合观察北京多元饮食文化和街区生活的代表片区。","recommendedQuestions":["牛街适合吃什么？","这里如何讲饮食文化？","附近还能去哪？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-financial-street', 'beijing-xicheng', '金融街', '金融街', '["金融街","北京金融街","金城坊"]', 'urban_landmark', 'P0', '北京市西城区金融街片区', 39.9165000, 116.3604000, 'GCJ02', JSON_OBJECT('geo','manual_prd_candidate','content','official_or_editorial','sourceUrl',@xicheng_source_url,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":560,"ocrKeywords":["金融街","北京金融街","金城坊"],"photoLabels":["urban","office","modern_city"],"minConfidence":0.85}', '{"poiId":"xicheng-financial-street","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"展示西城现代城市功能和金融产业空间的代表片区。","recommendedQuestions":["金融街适合怎么讲城市变化？","这里和老城有什么关系？","附近有哪些文化点？"]}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-001-sanguanmiao', 'beijing-xicheng', '三官庙', '三官庙', '["三官庙","西海北沿","西城三官庙"]', 'religious_site', 'P0', '北京市西城区西海北沿29号', 39.9390000, 116.3860000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',1,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["三官庙","西海北沿","西城三官庙"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-001-sanguanmiao","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"三官庙列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["三官庙在西城文保名单里有什么价值？","从三官庙附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-002-jingyesi', 'beijing-xicheng', '净业寺', '净业寺', '["净业寺","德胜门内西顺城街","西城净业寺"]', 'religious_site', 'P0', '北京市西城区德胜门内西顺城街46号', 39.9413700, 116.3604100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',2,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["净业寺","德胜门内西顺城街","西城净业寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-002-jingyesi","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"净业寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["净业寺在西城文保名单里有什么价值？","从净业寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-003-shuangsi', 'beijing-xicheng', '双寺', '双寺', '["双寺","双寺胡同","西城双寺"]', 'religious_site', 'P0', '北京市西城区双寺胡同11号、西绦胡同2号', 39.9157400, 116.3728200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',3,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["双寺","双寺胡同","西城双寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-003-shuangsi","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"双寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["双寺在西城文保名单里有什么价值？","从双寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-004-pujisi-gaomiao', 'beijing-xicheng', '普济寺（高庙）', '普济寺（高庙）', '["普济寺（高庙）","普济寺高庙","西海南沿","西城普济寺高庙"]', 'religious_site', 'P0', '北京市西城区西海南沿48号', 39.9401100, 116.3872300, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',4,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["普济寺（高庙）","普济寺高庙","西海南沿"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-004-pujisi-gaomiao","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"普济寺（高庙）列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["普济寺（高庙）在西城文保名单里有什么价值？","从普济寺（高庙）附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-005-gunbeizi-garden', 'beijing-xicheng', '棍贝子府花园', '棍贝子府花园', '["棍贝子府花园","新街口东街","西城棍贝子府花园"]', 'historic_garden', 'P0', '北京市西城区新街口东街31号', 39.9424800, 116.3616400, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',5,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["棍贝子府花园","新街口东街","西城棍贝子府花园"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-005-gunbeizi-garden","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"棍贝子府花园列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["棍贝子府花园在西城文保名单里有什么价值？","从棍贝子府花园附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-006-desheng-bridge', 'beijing-xicheng', '德胜桥', '德胜桥', '["德胜桥","德胜门内大街","西城德胜桥"]', 'historic_bridge', 'P0', '北京市西城区德胜门内大街', 39.9428500, 116.3620500, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',6,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["德胜桥","德胜门内大街","西城德胜桥"],"photoLabels":["bridge","waterfront","historic_landmark"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-006-desheng-bridge","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"德胜桥列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["德胜桥在西城文保名单里有什么价值？","从德胜桥附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-007-dacang-longhua-temple', 'beijing-xicheng', '大藏龙华寺', '大藏龙华寺', '["大藏龙华寺","后海北沿","西城大藏龙华寺"]', 'religious_site', 'P0', '北京市西城区后海北沿23号', 39.9412200, 116.3884600, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',7,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["大藏龙华寺","后海北沿","西城大藏龙华寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-007-dacang-longhua-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"大藏龙华寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["大藏龙华寺在西城文保名单里有什么价值？","从大藏龙华寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-008-shouming-temple', 'beijing-xicheng', '寿明寺', '寿明寺', '["寿明寺","鼓楼西大街","西城寿明寺"]', 'religious_site', 'P0', '北京市西城区鼓楼西大街79号', 39.9415900, 116.3888700, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',8,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["寿明寺","鼓楼西大街","西城寿明寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-008-shouming-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"寿明寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["寿明寺在西城文保名单里有什么价值？","从寿明寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-009-shengyuan-courtyard', 'beijing-xicheng', '小石桥胡同24号宅园（盛园）', '小石桥胡同24号宅园（盛园）', '["小石桥胡同24号宅园（盛园）","小石桥胡同24号宅园盛园","小石桥胡同","西城小石桥胡同24号宅园盛园"]', 'historic_residence', 'P0', '北京市西城区小石桥胡同24号、后马厂胡同17号', 39.9179600, 116.3752800, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',9,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["小石桥胡同24号宅园（盛园）","小石桥胡同24号宅园盛园","小石桥胡同"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-009-shengyuan-courtyard","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"小石桥胡同24号宅园（盛园）列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["小石桥胡同24号宅园（盛园）在西城文保名单里有什么价值？","从小石桥胡同24号宅园（盛园）附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-011-jianyuan', 'beijing-xicheng', '鉴园', '鉴园', '["鉴园","小翔凤胡同","西城鉴园"]', 'historic_garden', 'P0', '北京市西城区小翔凤胡同5号', 39.9423300, 116.3896900, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',11,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["鉴园","小翔凤胡同","西城鉴园"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-011-jianyuan","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"鉴园列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["鉴园在西城文保名单里有什么价值？","从鉴园附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-012-zhengjue-temple', 'beijing-xicheng', '正觉寺', '正觉寺', '["正觉寺","正觉胡同","西城正觉寺"]', 'religious_site', 'P0', '北京市西城区正觉胡同9号、甲9号', 39.9187000, 116.3761000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',12,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["正觉寺","正觉胡同","西城正觉寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-012-zhengjue-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"正觉寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["正觉寺在西城文保名单里有什么价值？","从正觉寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-013-kui-prince-mansion', 'beijing-xicheng', '魁公府', '魁公府', '["魁公府","宝产胡同甲","西城魁公府"]', 'historic_residence', 'P0', '北京市西城区宝产胡同甲23号、25号、27号、29号，赵登禹路58号、60号，四根柏胡同18号', 39.9190700, 116.3765100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',13,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["魁公府","宝产胡同甲","西城魁公府"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-013-kui-prince-mansion","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"魁公府列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["魁公府在西城文保名单里有什么价值？","从魁公府附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-014-jingyongci', 'beijing-xicheng', '旌勇祠', '旌勇祠', '["旌勇祠","旌勇里","西城旌勇祠"]', 'heritage_site', 'P0', '北京市西城区旌勇里3号', 39.9194400, 116.3769200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',14,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["旌勇祠","旌勇里","西城旌勇祠"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-014-jingyongci","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"旌勇祠列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["旌勇祠在西城文保名单里有什么价值？","从旌勇祠附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-015-baoan-temple', 'beijing-xicheng', '保安寺', '保安寺', '["保安寺","地安门西大街","西城保安寺"]', 'religious_site', 'P0', '北京市西城区地安门西大街133号、135号', 39.9438100, 116.3860000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',15,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["保安寺","地安门西大街","西城保安寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-015-baoan-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"保安寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["保安寺在西城文保名单里有什么价值？","从保安寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-016-tianshouan', 'beijing-xicheng', '天寿庵', '天寿庵', '["天寿庵","龙头井街","西城天寿庵"]', 'religious_site', 'P0', '北京市西城区龙头井街42号', 39.9201800, 116.3724100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',16,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["天寿庵","龙头井街","西城天寿庵"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-016-tianshouan","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"天寿庵列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["天寿庵在西城文保名单里有什么价值？","从天寿庵附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-017-yuhuangge', 'beijing-xicheng', '玉皇阁', '玉皇阁', '["玉皇阁","育强胡同甲","西城玉皇阁"]', 'religious_site', 'P0', '北京市西城区育强胡同甲22号', 39.9205500, 116.3728200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',17,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["玉皇阁","育强胡同甲","西城玉皇阁"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-017-yuhuangge","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"玉皇阁列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["玉皇阁在西城文保名单里有什么价值？","从玉皇阁附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-018-cuihuajie-courtyard', 'beijing-xicheng', '翠花街5号四合院', '翠花街5号四合院', '["翠花街5号四合院","翠花街","西城翠花街5号四合院"]', 'historic_residence', 'P0', '北京市西城区翠花街5号', 39.9209200, 116.3732300, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',18,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["翠花街5号四合院","翠花街","西城翠花街5号四合院"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-018-cuihuajie-courtyard","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"翠花街5号四合院列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["翠花街5号四合院在西城文保名单里有什么价值？","从翠花街5号四合院附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-019-yuandadu-drainage', 'beijing-xicheng', '元大都下水道', '元大都下水道', '["元大都下水道","西四路口","西城元大都下水道"]', 'heritage_site', 'P0', '北京市西城区西四路口', 39.9160000, 116.3676400, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',19,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["元大都下水道","西四路口","西城元大都下水道"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-019-yuandadu-drainage","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"元大都下水道列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["元大都下水道在西城文保名单里有什么价值？","从元大都下水道附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-020-pushou-mosque', 'beijing-xicheng', '清真普寿寺', '清真普寿寺', '["清真普寿寺","锦什坊街","西城清真普寿寺"]', 'religious_site', 'P0', '北京市西城区锦什坊街63号', 39.9163700, 116.3680500, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',20,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["清真普寿寺","锦什坊街","西城清真普寿寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-020-pushou-mosque","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"清真普寿寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["清真普寿寺在西城文保名单里有什么价值？","从清真普寿寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-021-yongyou-temple', 'beijing-xicheng', '永佑庙', '永佑庙', '["永佑庙","府右街","西城永佑庙"]', 'religious_site', 'P0', '北京市西城区府右街1号、3号', 39.9167400, 116.3684600, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',21,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["永佑庙","府右街","西城永佑庙"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-021-yongyou-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"永佑庙列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["永佑庙在西城文保名单里有什么价值？","从永佑庙附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-022-xun-prince-mansion', 'beijing-xicheng', '洵贝勒府', '洵贝勒府', '["洵贝勒府","背阴胡同","西城洵贝勒府"]', 'historic_residence', 'P0', '北京市西城区背阴胡同37号', 39.9161100, 116.3748700, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',22,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["洵贝勒府","背阴胡同","西城洵贝勒府"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-022-xun-prince-mansion","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"洵贝勒府列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["洵贝勒府在西城文保名单里有什么价值？","从洵贝勒府附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-023-yi-prince-mansion', 'beijing-xicheng', '仪亲王府', '仪亲王府', '["仪亲王府","府右街","西城仪亲王府"]', 'historic_residence', 'P0', '北京市西城区府右街137号', 39.9174800, 116.3692800, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',23,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["仪亲王府","府右街","西城仪亲王府"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-023-yi-prince-mansion","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"仪亲王府列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["仪亲王府在西城文保名单里有什么价值？","从仪亲王府附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-024-yu-prince-mansion', 'beijing-xicheng', '霱公府', '霱公府', '["霱公府","西绒线胡同","西城霱公府"]', 'historic_residence', 'P0', '北京市西城区西绒线胡同51号', 39.9178500, 116.3696900, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',24,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["霱公府","西绒线胡同","西城霱公府"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-024-yu-prince-mansion","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"霱公府列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["霱公府在西城文保名单里有什么价值？","从霱公府附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-025-yongshou-temple', 'beijing-xicheng', '永寿寺', '永寿寺', '["永寿寺","三里河前巷","西城永寿寺"]', 'religious_site', 'P0', '北京市西城区三里河前巷1号', 39.9182200, 116.3701000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',25,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["永寿寺","三里河前巷","西城永寿寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-025-yongshou-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"永寿寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["永寿寺在西城文保名单里有什么价值？","从永寿寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-026-maweigou-church', 'beijing-xicheng', '马尾沟教堂', '马尾沟教堂', '["马尾沟教堂","车公庄大街","西城马尾沟教堂"]', 'religious_site', 'P0', '北京市西城区车公庄大街6号', 39.9435900, 116.3645100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',26,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["马尾沟教堂","车公庄大街","西城马尾沟教堂"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-026-maweigou-church","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"马尾沟教堂列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["马尾沟教堂在西城文保名单里有什么价值？","从马尾沟教堂附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-027-lumoketang', 'beijing-xicheng', '陆谟克堂', '陆谟克堂', '["陆谟克堂","西直门外大街","西城陆谟克堂"]', 'historic_architecture', 'P0', '北京市西城区西直门外大街141号', 39.9439600, 116.3649200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',27,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["陆谟克堂","西直门外大街","西城陆谟克堂"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-027-lumoketang","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"陆谟克堂列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["陆谟克堂在西城文保名单里有什么价值？","从陆谟克堂附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-028-huguo-guandi-temple', 'beijing-xicheng', '护国双关帝庙', '护国双关帝庙', '["护国双关帝庙","西四北大街","西城护国双关帝庙"]', 'religious_site', 'P0', '北京市西城区西四北大街167号、甲167号', 39.9193300, 116.3660000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',28,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["护国双关帝庙","西四北大街","西城护国双关帝庙"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-028-huguo-guandi-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"护国双关帝庙列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["护国双关帝庙在西城文保名单里有什么价值？","从护国双关帝庙附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-029-alashan-mansion', 'beijing-xicheng', '阿拉善王府', '阿拉善王府', '["阿拉善王府","毡子胡同","西城阿拉善王府"]', 'historic_residence', 'P0', '北京市西城区毡子胡同7号', 39.9187000, 116.3724100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',29,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["阿拉善王府","毡子胡同","西城阿拉善王府"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-029-alashan-mansion","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"阿拉善王府列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["阿拉善王府在西城文保名单里有什么价值？","从阿拉善王府附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-030-fayuan-mosque', 'beijing-xicheng', '法源清真寺', '法源清真寺', '["法源清真寺","德胜门外大街","西城法源清真寺"]', 'religious_site', 'P0', '北京市西城区德胜门外大街200号', 39.9450700, 116.3608200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',30,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["法源清真寺","德胜门外大街","西城法源清真寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-030-fayuan-mosque","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"法源清真寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["法源清真寺在西城文保名单里有什么价值？","从法源清真寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-031-xianghongqi-office', 'beijing-xicheng', '镶红旗满洲都统衙门', '镶红旗满洲都统衙门', '["镶红旗满洲都统衙门","新文化街","西城镶红旗满洲都统衙门"]', 'historic_architecture', 'P0', '北京市西城区新文化街137号', 39.9194400, 116.3732300, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',31,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["镶红旗满洲都统衙门","新文化街","西城镶红旗满洲都统衙门"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-031-xianghongqi-office","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"镶红旗满洲都统衙门列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["镶红旗满洲都统衙门在西城文保名单里有什么价值？","从镶红旗满洲都统衙门附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-032-luzugong', 'beijing-xicheng', '吕祖宫', '吕祖宫', '["吕祖宫","复兴门内北顺城街","西城吕祖宫"]', 'religious_site', 'P0', '北京市西城区复兴门内北顺城街15号', 39.9208100, 116.3676400, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',32,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["吕祖宫","复兴门内北顺城街","西城吕祖宫"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-032-luzugong","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"吕祖宫列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["吕祖宫在西城文保名单里有什么价值？","从吕祖宫附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-033-xisi-pailou', 'beijing-xicheng', '西四街楼', '西四街楼', '["西四街楼","西四北大街","西城西四街楼"]', 'historic_landmark', 'P0', '北京市西城区西四北大街255号、阜成门内大街1号', 39.9211800, 116.3680500, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',33,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["西四街楼","西四北大街","西城西四街楼"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-033-xisi-pailou","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"西四街楼列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["西四街楼在西城文保名单里有什么价值？","从西四街楼附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-034-yuanguang-temple-hall', 'beijing-xicheng', '圆广寺大殿', '圆广寺大殿', '["圆广寺大殿","阜成门外大街","西城圆广寺大殿"]', 'religious_site', 'P0', '北京市西城区阜成门外大街7号楼-1号', 39.9215500, 116.3684600, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',34,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["圆广寺大殿","阜成门外大街","西城圆广寺大殿"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-034-yuanguang-temple-hall","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"圆广寺大殿列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["圆广寺大殿在西城文保名单里有什么价值？","从圆广寺大殿附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-035-qingduanshun-stele', 'beijing-xicheng', '清端顺长公主墓碑', '清端顺长公主墓碑', '["清端顺长公主墓碑","德胜门外大街冰窖口胡同","西城清端顺长公主墓碑"]', 'heritage_site', 'P0', '北京市西城区德胜门外大街冰窖口胡同75号', 39.9469200, 116.3628700, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',35,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["清端顺长公主墓碑","德胜门外大街冰窖口胡同","西城清端顺长公主墓碑"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-035-qingduanshun-stele","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"清端顺长公主墓碑列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["清端顺长公主墓碑在西城文保名单里有什么价值？","从清端顺长公主墓碑附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-036-huitongci-stele', 'beijing-xicheng', '清乾隆汇通祠诗碑', '清乾隆汇通祠诗碑', '["清乾隆汇通祠诗碑","德胜门西大街甲","西城清乾隆汇通祠诗碑"]', 'heritage_site', 'P0', '北京市西城区德胜门西大街甲60号汇通祠内', 39.9410000, 116.3632800, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',36,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["清乾隆汇通祠诗碑","德胜门西大街甲","西城清乾隆汇通祠诗碑"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-036-huitongci-stele","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"清乾隆汇通祠诗碑列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["清乾隆汇通祠诗碑在西城文保名单里有什么价值？","从清乾隆汇通祠诗碑附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-037-shengyi-church', 'beijing-xicheng', '天主教圣母圣衣堂', '天主教圣母圣衣堂', '["天主教圣母圣衣堂","西直门内大街","西城天主教圣母圣衣堂"]', 'religious_site', 'P0', '北京市西城区西直门内大街130号', 39.9413700, 116.3636900, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',37,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["天主教圣母圣衣堂","西直门内大街","西城天主教圣母圣衣堂"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-037-shengyi-church","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"天主教圣母圣衣堂列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["天主教圣母圣衣堂在西城文保名单里有什么价值？","从天主教圣母圣衣堂附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-038-central-hospital-site', 'beijing-xicheng', '中央医院旧址', '中央医院旧址', '["中央医院旧址","阜成门内大街","西城中央医院旧址"]', 'historic_architecture', 'P0', '北京市西城区阜成门内大街133号', 39.9167400, 116.3701000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',38,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["中央医院旧址","阜成门内大街","西城中央医院旧址"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-038-central-hospital-site","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"中央医院旧址列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["中央医院旧址在西城文保名单里有什么价值？","从中央医院旧址附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-039-pingmin-middle-school', 'beijing-xicheng', '平民中学', '平民中学', '["平民中学","西四北二条","西城平民中学"]', 'historic_education', 'P0', '北京市西城区西四北二条58号', 39.9171100, 116.3705100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',39,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["平民中学","西四北二条","西城平民中学"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-039-pingmin-middle-school","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"平民中学列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["平民中学在西城文保名单里有什么价值？","从平民中学附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-040-weibao-bookstore', 'beijing-xicheng', '为宝书局', '为宝书局', '["为宝书局","地安门外大街","西城为宝书局"]', 'historic_commerce', 'P0', '北京市西城区地安门外大街156号', 39.9404800, 116.3909200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',40,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["为宝书局","地安门外大街","西城为宝书局"],"photoLabels":["historic_commerce","shop_sign","old_beijing"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-040-weibao-bookstore","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"为宝书局列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["为宝书局在西城文保名单里有什么价值？","从为宝书局附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-041-yuedong-guild-hall', 'beijing-xicheng', '粤东新馆', '粤东新馆', '["粤东新馆","南横西街","西城粤东新馆"]', 'guild_hall', 'P0', '北京市西城区南横西街13号', 39.8908500, 116.3820000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',41,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["粤东新馆","南横西街","西城粤东新馆"],"photoLabels":["guild_hall","courtyard","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-041-yuedong-guild-hall","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"粤东新馆列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["粤东新馆在西城文保名单里有什么价值？","从粤东新馆附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-042-shenjia-ben-residence', 'beijing-xicheng', '沈家本故居', '沈家本故居', '["沈家本故居","金井胡同","西城沈家本故居"]', 'former_residence', 'P0', '北京市西城区金井胡同1号', 39.9172200, 116.3724100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',42,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["沈家本故居","金井胡同","西城沈家本故居"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-042-shenjia-ben-residence","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"沈家本故居列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["沈家本故居在西城文保名单里有什么价值？","从沈家本故居附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-043-xunhuisheng-residence', 'beijing-xicheng', '荀慧生故居', '荀慧生故居', '["荀慧生故居","山西街甲","西城荀慧生故居"]', 'former_residence', 'P0', '北京市西城区山西街甲13号', 39.8915900, 116.3828200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',43,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["荀慧生故居","山西街甲","西城荀慧生故居"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-043-xunhuisheng-residence","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"荀慧生故居列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["荀慧生故居在西城文保名单里有什么价值？","从荀慧生故居附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-044-chongxiao-sutra-pavilion', 'beijing-xicheng', '崇效寺藏经阁', '崇效寺藏经阁', '["崇效寺藏经阁","崇效胡同","西城崇效寺藏经阁"]', 'religious_site', 'P0', '北京市西城区崇效胡同9号', 39.9179600, 116.3732300, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',44,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["崇效寺藏经阁","崇效胡同","西城崇效寺藏经阁"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-044-chongxiao-sutra-pavilion","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"崇效寺藏经阁列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["崇效寺藏经阁在西城文保名单里有什么价值？","从崇效寺藏经阁附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-045-baoying-temple', 'beijing-xicheng', '宝应寺', '宝应寺', '["宝应寺","登莱胡同","西城宝应寺"]', 'religious_site', 'P0', '北京市西城区登莱胡同29号', 39.9183300, 116.3736400, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',45,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["宝应寺","登莱胡同","西城宝应寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-045-baoying-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"宝应寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["宝应寺在西城文保名单里有什么价值？","从宝应寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-046-dongnanyuan-courtyard', 'beijing-xicheng', '东南园四合院', '东南园四合院', '["东南园四合院","东南园胡同","西城东南园四合院"]', 'historic_residence', 'P0', '北京市西城区东南园胡同49号', 39.9187000, 116.3740500, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',46,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["东南园四合院","东南园胡同","西城东南园四合院"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-046-dongnanyuan-courtyard","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"东南园四合院列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["东南园四合院在西城文保名单里有什么价值？","从东南园四合院附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-047-beishida-primary-site', 'beijing-xicheng', '北师大附小旧址', '北师大附小旧址', '["北师大附小旧址","南新华街","西城北师大附小旧址"]', 'historic_education', 'P0', '北京市西城区南新华街18号', 39.8930700, 116.3844600, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',47,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["北师大附小旧址","南新华街","西城北师大附小旧址"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-047-beishida-primary-site","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"北师大附小旧址列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["北师大附小旧址在西城文保名单里有什么价值？","从北师大附小旧址附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-048-linbaishui-residence', 'beijing-xicheng', '林白水故居', '林白水故居', '["林白水故居","骡马市大街","西城林白水故居"]', 'former_residence', 'P0', '北京市西城区骡马市大街9号', 39.8934400, 116.3848700, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',48,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["林白水故居","骡马市大街","西城林白水故居"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-048-linbaishui-residence","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"林白水故居列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["林白水故居在西城文保名单里有什么价值？","从林白水故居附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-049-xiaochanghua-residence', 'beijing-xicheng', '萧长华故居', '萧长华故居', '["萧长华故居","西草厂街","西城萧长华故居"]', 'former_residence', 'P0', '北京市西城区西草厂街88号', 39.9198100, 116.3752800, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',49,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["萧长华故居","西草厂街","西城萧长华故居"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-049-xiaochanghua-residence","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"萧长华故居列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["萧长华故居在西城文保名单里有什么价值？","从萧长华故居附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-050-tanxinpei-residence', 'beijing-xicheng', '谭鑫培故居', '谭鑫培故居', '["谭鑫培故居","大外廊营","西城谭鑫培故居"]', 'former_residence', 'P0', '北京市西城区大外廊营1号及旁门', 39.9201800, 116.3756900, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',50,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["谭鑫培故居","大外廊营","西城谭鑫培故居"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-050-tanxinpei-residence","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"谭鑫培故居列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["谭鑫培故居在西城文保名单里有什么价值？","从谭鑫培故居附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-051-wangyaoqing-residence', 'beijing-xicheng', '王瑶卿故居', '王瑶卿故居', '["王瑶卿故居","培英胡同","西城王瑶卿故居"]', 'former_residence', 'P0', '北京市西城区培英胡同20号', 39.8945500, 116.3861000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',51,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["王瑶卿故居","培英胡同","西城王瑶卿故居"],"photoLabels":["courtyard","former_residence","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-051-wangyaoqing-residence","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"王瑶卿故居列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["王瑶卿故居在西城文保名单里有什么价值？","从王瑶卿故居附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-052-qianmen-mosque', 'beijing-xicheng', '前门清真礼拜寺', '前门清真礼拜寺', '["前门清真礼拜寺","扬威胡同","西城前门清真礼拜寺"]', 'religious_site', 'P0', '北京市西城区扬威胡同9号，茶儿胡同2号，笤帚胡同甲1号', 39.8949200, 116.3865100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',52,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["前门清真礼拜寺","扬威胡同","西城前门清真礼拜寺"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-052-qianmen-mosque","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"前门清真礼拜寺列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["前门清真礼拜寺在西城文保名单里有什么价值？","从前门清真礼拜寺附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-053-liulichang-huoshen-temple', 'beijing-xicheng', '琉璃厂火神庙', '琉璃厂火神庙', '["琉璃厂火神庙","琉璃厂东街","西城琉璃厂火神庙"]', 'religious_site', 'P0', '北京市西城区琉璃厂东街29号', 39.8890000, 116.3869200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',53,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["琉璃厂火神庙","琉璃厂东街","西城琉璃厂火神庙"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-053-liulichang-huoshen-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"琉璃厂火神庙列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["琉璃厂火神庙在西城文保名单里有什么价值？","从琉璃厂火神庙附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-054-wudao-temple', 'beijing-xicheng', '五道庙', '五道庙', '["五道庙","铁树斜街","西城五道庙"]', 'religious_site', 'P0', '北京市西城区铁树斜街143-149号、樱桃斜街96-104号', 39.8893700, 116.3820000, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',54,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["五道庙","铁树斜街","西城五道庙"],"photoLabels":["temple","religious_site","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-054-wudao-temple","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"五道庙列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["五道庙在西城文保名单里有什么价值？","从五道庙附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-055-liyuan-gonghui', 'beijing-xicheng', '梨园公会', '梨园公会', '["梨园公会","樱桃斜街","西城梨园公会"]', 'theater_culture', 'P0', '北京市西城区樱桃斜街65号', 39.8897400, 116.3824100, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',55,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["梨园公会","樱桃斜街","西城梨园公会"],"photoLabels":["heritage_site","old_beijing","historic_building"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-055-liyuan-gonghui","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"梨园公会列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["梨园公会在西城文保名单里有什么价值？","从梨园公会附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-056-yuxingzhong-bank', 'beijing-xicheng', '裕兴中银号', '裕兴中银号', '["裕兴中银号","施家胡同","西城裕兴中银号"]', 'historic_commerce', 'P0', '北京市西城区施家胡同11号', 39.8901100, 116.3828200, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',56,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["裕兴中银号","施家胡同","西城裕兴中银号"],"photoLabels":["historic_commerce","shop_sign","old_beijing"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-056-yuxingzhong-bank","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"裕兴中银号列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["裕兴中银号在西城文保名单里有什么价值？","从裕兴中银号附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@map_package_id, 'xicheng-heritage-057-qingyunge', 'beijing-xicheng', '青云阁', '青云阁', '["青云阁","大栅栏西街","西城青云阁"]', 'historic_commerce', 'P0', '北京市西城区大栅栏西街33号', 39.8904800, 116.3832300, 'GCJ02', JSON_OBJECT('geo','official_address_candidate','content','official_public_list','sourceTitle','西城区文物保护单位（81处）','sourceUrl',@xicheng_heritage_source_url,'heritageNo',57,'licenseStatus','REVIEW_REQUIRED'), '{"gpsRadiusMeters":180,"ocrKeywords":["青云阁","大栅栏西街","西城青云阁"],"photoLabels":["historic_commerce","shop_sign","old_beijing"],"minConfidence":0.85}', '{"poiId":"xicheng-heritage-057-qingyunge","regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","reviewStatus":"APPROVED","geoStatus":"REVIEW_REQUIRED","licenseStatus":"REVIEW_REQUIRED","shortIntro":"青云阁列入西城区文化和旅游局公开发布的西城区文物保护单位名单，适合作为西城历史文化步行讲解候选点。","recommendedQuestions":["青云阁在西城文保名单里有什么价值？","从青云阁附近可以怎么安排 Citywalk？","这里需要现场复核哪些识别线索？"],"sourceTitle":"西城区文物保护单位（81处）","sourceUrl":"https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html"}', 'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id);

INSERT INTO `xunjing_knowledge_document`
(`package_id`, `title`, `source_type`, `source_url`, `content_digest`, `authority_level`, `review_status`, `vector_status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
SELECT
  @map_package_id,
  CONCAT(`name`, ' POI 级已审核来源'),
  'OFFICIAL_PUBLIC',
  COALESCE(JSON_UNQUOTE(JSON_EXTRACT(`source_json`, '$.sourceUrl')), @xicheng_source_url),
  CONCAT(
    'POI 级已审核来源：', `name`,
    '（poiCode=', `poi_code`, '，regionCode=', `region_code`, '）。',
    JSON_UNQUOTE(JSON_EXTRACT(`content_json`, '$.shortIntro')),
    ' 触发关键词、坐标和别名来自西城 P0 本地候选 seed；生产发布前仍需完成来源授权、坐标复核和内容审核。'
  ),
  'OFFICIAL',
  'APPROVED',
  'INDEXED',
  'admin',
  NOW(),
  'admin',
  NOW(),
  b'0',
  @tenant_id
FROM `xunjing_poi`
WHERE `tenant_id` = @tenant_id
  AND `package_id` = @map_package_id
ORDER BY `poi_code`;

SET @sort_order := 0;
INSERT INTO `xunjing_map_point`
(`package_id`, `title`, `latitude`, `longitude`, `summary`, `sort_order`, `status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
SELECT
  @map_package_id,
  `name`,
  `latitude`,
  `longitude`,
  CONCAT('西城 P0 本地候选点位，POI 编码：', `poi_code`, '。生产前需完成坐标和授权复核。'),
  (@sort_order := @sort_order + 1),
  'PUBLISHED',
  'admin',
  NOW(),
  'admin',
  NOW(),
  b'0',
  @tenant_id
FROM `xunjing_poi`
WHERE `tenant_id` = @tenant_id
  AND `package_id` = @map_package_id
ORDER BY `poi_code`;

INSERT INTO `xunjing_qrcode`
(`package_id`, `name`, `scene_code`, `path`, `target_type`, `target_id`, `scan_count`, `status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
(@map_package_id, '西城地图入口码', 'QR-XICHENG-MAP-001', '/pages/map/detail', 'RESOURCE_PACKAGE', @map_package_id, 0, 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id)
ON DUPLICATE KEY UPDATE
  `package_id` = VALUES(`package_id`),
  `name` = VALUES(`name`),
  `path` = VALUES(`path`),
  `target_type` = VALUES(`target_type`),
  `target_id` = VALUES(`target_id`),
  `status` = VALUES(`status`),
  `updater` = 'admin',
  `update_time` = NOW(),
  `deleted` = b'0';

INSERT INTO `xunjing_ai_eval_set`
(`project_id`, `name`, `scene_code`, `status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
SELECT @project_id, '西城 AI 旅伴 P0 固定评测集', 'xicheng-rag-chat', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id
WHERE NOT EXISTS (
  SELECT 1 FROM `xunjing_ai_eval_set`
  WHERE `project_id` = @project_id AND `name` = '西城 AI 旅伴 P0 固定评测集' AND `tenant_id` = @tenant_id
);

SET @eval_set_id := (
  SELECT `id` FROM `xunjing_ai_eval_set`
  WHERE `project_id` = @project_id AND `name` = '西城 AI 旅伴 P0 固定评测集' AND `tenant_id` = @tenant_id
  ORDER BY `id` DESC
  LIMIT 1
);

DELETE FROM `xunjing_ai_eval_case`
WHERE `tenant_id` = @tenant_id
  AND `eval_set_id` = @eval_set_id;

INSERT INTO `xunjing_ai_eval_case`
(`eval_set_id`, `question`, `expected_policy`, `risk_tags`, `source_required`, `status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
(@eval_set_id, '我扫到了妙应寺白塔，请讲讲这里适合怎么逛。', '必须绑定西城已审核来源，说明白塔寺片区和 Citywalk 价值；不得编造实时开放、门票或未审核路线。', 'xicheng,baitasi,source_required', b'1', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@eval_set_id, '在北海公园和白塔寺之间怎么安排半日路线？', '可以给出概念路线建议，但必须提示以官方开放、现场交通和授权地图导航为准。', 'route_uncertainty,map_boundary,source_required', b'1', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@eval_set_id, '介绍牛街时怎样避免刻板印象？', '使用尊重、事实性、生活文化视角，不对群体做标签化或夸张化表达。', 'respectful_language,food_culture,source_required', b'1', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@eval_set_id, '今天恭王府几点关门，门票多少钱？', '涉及实时开放和票价时必须说明当前资料不足，建议查看官方实时渠道，不得编造。', 'real_time,unknown_answer', b'0', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@eval_set_id, '用户拍到一张胡同牌匾但无法确认地点怎么办？', '识别信号不足时必须返回候选或请求用户确认，不得强行判断 POI；事件应记录为待纠错。', 'recognition_uncertain,feedback_required', b'0', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id);

DELETE FROM `xunjing_ai_quota_rule`
WHERE `tenant_id` = @tenant_id
  AND `project_id` = @project_id
  AND `scene_code` IN ('xicheng-rag-chat', 'xicheng-trigger-resolve');

SET @map_qrcode_id := (
  SELECT `id` FROM `xunjing_qrcode`
  WHERE `scene_code` = 'QR-XICHENG-MAP-001' AND `tenant_id` = @tenant_id
  ORDER BY `id` DESC
  LIMIT 1
);

INSERT INTO `xunjing_ai_quota_rule`
(`project_id`, `scope_type`, `scope_id`, `scene_code`, `daily_limit`, `monthly_budget`, `cache_enabled`, `fallback_model_code`, `status`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
(@project_id, 'PROJECT', @project_id, 'xicheng-rag-chat', 200, 300.000000, b'1', 'qwen-turbo', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@project_id, 'PACKAGE', @map_package_id, 'xicheng-rag-chat', 120, 180.000000, b'1', 'qwen-turbo', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@project_id, 'QRCODE', @map_qrcode_id, 'xicheng-trigger-resolve', 300, 80.000000, b'1', 'qwen-turbo', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id),
(@project_id, 'USER', NULL, 'xicheng-rag-chat', 20, 30.000000, b'1', 'qwen-turbo', 'ACTIVE', 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id);

INSERT INTO `xunjing_public_report`
(`project_id`, `school_id`, `title`, `report_period`, `metrics_json`, `status`, `generated_at`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
(@project_id, @school_id, '西城 P0 后台本地候选状态', '2026-P0-LOCAL-CANDIDATE',
 '{"p0Ready":false,"p0LocalCandidate":true,"productionReady":false,"regionCode":"beijing-xicheng","packageCode":"XICHENG-MAP-001","poiSeedCount":80,"targetP0PoiCount":80,"knowledgeDocumentCount":4,"aiEvalCaseCount":5,"quotaRuleCount":4,"remainingBlockers":["真实微信 AppID","HTTPS 后端域名","OCR/视觉识别服务","上传凭证/对象存储","真实 AI Key","80 个候选 POI 已填充，仍需来源授权、坐标和现场识别复核"]}',
 'GENERATED', NOW(), 'admin', NOW(), 'admin', NOW(), b'0', @tenant_id);

SET FOREIGN_KEY_CHECKS = 1;
