CREATE TABLE IF NOT EXISTS "xunjing_project" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(128) NOT NULL,
    "region_name" varchar(128),
    "phase" varchar(32) NOT NULL,
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_school" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(128) NOT NULL,
    "region_name" varchar(128),
    "contact_name" varchar(64),
    "contact_phone" varchar(64),
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_resource_package" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "project_id" bigint NOT NULL,
    "school_id" bigint NOT NULL,
    "package_code" varchar(64) NOT NULL,
    "title" varchar(128) NOT NULL,
    "resource_type" varchar(32) NOT NULL,
    "version_no" varchar(32) NOT NULL,
    "ai_knowledge_id" bigint,
    "status" varchar(32) NOT NULL,
    "published_at" timestamp,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_knowledge_document" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "package_id" bigint NOT NULL,
    "title" varchar(256) NOT NULL,
    "source_type" varchar(32) NOT NULL,
    "source_url" varchar(1024),
    "content_digest" clob,
    "authority_level" varchar(32) NOT NULL,
    "review_status" varchar(32) NOT NULL,
    "vector_status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_media_asset" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "package_id" bigint NOT NULL,
    "title" varchar(256) NOT NULL,
    "media_type" varchar(32) NOT NULL,
    "file_url" varchar(1024),
    "object_key" varchar(512),
    "source_provider" varchar(128),
    "source_url" varchar(1024),
    "copyright_status" varchar(32) NOT NULL,
    "review_status" varchar(32) NOT NULL,
    "image_tags" varchar(1024),
    "can_public" boolean NOT NULL DEFAULT TRUE,
    "can_ai_use" boolean NOT NULL DEFAULT TRUE,
    "can_promotion_use" boolean NOT NULL DEFAULT FALSE,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_media_usage_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "media_id" bigint NOT NULL,
    "package_id" bigint NOT NULL,
    "scene_code" varchar(64) NOT NULL,
    "usage_type" varchar(32) NOT NULL,
    "caller" varchar(64),
    "payload_json" clob,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_map_point" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "package_id" bigint NOT NULL,
    "title" varchar(128) NOT NULL,
    "latitude" decimal(10, 7),
    "longitude" decimal(10, 7),
    "summary" varchar(1024),
    "sort_order" int DEFAULT 0,
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_poi" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "package_id" bigint NOT NULL,
    "poi_code" varchar(64) NOT NULL,
    "region_code" varchar(64) NOT NULL,
    "name" varchar(128) NOT NULL,
    "official_name" varchar(128),
    "aliases_json" clob,
    "category" varchar(64) NOT NULL,
    "poi_level" varchar(32) NOT NULL,
    "address" varchar(255),
    "latitude" decimal(10, 7),
    "longitude" decimal(10, 7),
    "coord_type" varchar(16) NOT NULL DEFAULT 'GCJ02',
    "source_json" clob,
    "trigger_json" clob,
    "content_json" clob,
    "review_status" varchar(32) NOT NULL DEFAULT 'DRAFT',
    "geo_status" varchar(32) NOT NULL DEFAULT 'REVIEW_REQUIRED',
    "license_status" varchar(32) NOT NULL DEFAULT 'REVIEW_REQUIRED',
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_globe_model" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "package_id" bigint NOT NULL,
    "title" varchar(128) NOT NULL,
    "model_url" varchar(1024),
    "cover_url" varchar(1024),
    "data_version" varchar(32),
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_interaction_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "package_id" bigint NOT NULL,
    "school_id" bigint,
    "event_type" varchar(32) NOT NULL,
    "source_channel" varchar(32),
    "user_trace_id" varchar(128),
    "payload_json" clob,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_qrcode" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "package_id" bigint NOT NULL,
    "name" varchar(128) NOT NULL,
    "scene_code" varchar(64) NOT NULL,
    "path" varchar(255) NOT NULL,
    "target_type" varchar(32) NOT NULL,
    "target_id" bigint NOT NULL,
    "scan_count" bigint NOT NULL DEFAULT 0,
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_public_report" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "project_id" bigint NOT NULL,
    "school_id" bigint,
    "title" varchar(128) NOT NULL,
    "report_period" varchar(32) NOT NULL,
    "metrics_json" clob,
    "status" varchar(32) NOT NULL,
    "generated_at" timestamp,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_crawler_source" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "project_id" bigint NOT NULL,
    "package_id" bigint NOT NULL,
    "source_url" varchar(1024) NOT NULL,
    "host" varchar(255),
    "source_kind" varchar(32) NOT NULL,
    "connector" varchar(64) NOT NULL,
    "source_lane" varchar(64) NOT NULL,
    "capture_profile" varchar(64) NOT NULL,
    "fact_source_policy" varchar(128) NOT NULL,
    "capture_assets" bit NOT NULL DEFAULT FALSE,
    "metadata_only" bit NOT NULL DEFAULT FALSE,
    "status" varchar(32) NOT NULL,
    "blocked_reason_hint" varchar(256),
    "notes" clob,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_import_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "source_id" bigint,
    "project_id" bigint NOT NULL,
    "package_id" bigint NOT NULL,
    "item_type" varchar(32) NOT NULL,
    "item_title" varchar(256) NOT NULL,
    "original_url" varchar(1024),
    "file_url" varchar(1024),
    "source_provider" varchar(128),
    "evidence_text" clob,
    "target_type" varchar(32),
    "target_id" bigint,
    "review_status" varchar(32) NOT NULL,
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_ai_eval_set" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "project_id" bigint NOT NULL,
    "name" varchar(128) NOT NULL,
    "scene_code" varchar(64) NOT NULL,
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_ai_eval_case" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "eval_set_id" bigint NOT NULL,
    "question" varchar(512) NOT NULL,
    "expected_policy" clob NOT NULL,
    "risk_tags" varchar(512),
    "source_required" bit NOT NULL DEFAULT TRUE,
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_ai_quota_rule" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "project_id" bigint NOT NULL,
    "scope_type" varchar(32) NOT NULL,
    "scope_id" bigint,
    "scene_code" varchar(64) NOT NULL,
    "daily_limit" int NOT NULL,
    "monthly_budget" decimal(18, 6),
    "cache_enabled" bit NOT NULL DEFAULT TRUE,
    "fallback_model_code" varchar(64),
    "status" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "xunjing_ai_generation_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "project_id" bigint NOT NULL,
    "school_id" bigint,
    "package_id" bigint NOT NULL,
    "qr_code_id" bigint,
    "scene_code" varchar(64) NOT NULL,
    "user_trace_id" varchar(128),
    "model_code" varchar(64) NOT NULL,
    "prompt_version" varchar(64),
    "input_summary" clob,
    "output_summary" clob,
    "source_json" clob,
    "token_count" bigint NOT NULL DEFAULT 0,
    "cost_amount" decimal(18, 6) NOT NULL DEFAULT 0,
    "safety_status" varchar(32) NOT NULL,
    "cache_hit" bit NOT NULL DEFAULT FALSE,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);
