import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, test } from 'vitest'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const xichengSeedPath = 'backend/yudao/sql/mysql/xunjing-seed-xicheng-p0.sql'

async function readText(path) {
  return await readFile(resolve(rootDir, path), 'utf8')
}

function xichengPoiSeedRows(seed) {
  return seed
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith("(@map_package_id, 'xicheng-"))
}

describe('xicheng backend launch readiness', () => {
  test('gates Xicheng P0 backend launch seed and verifier coverage', async () => {
    expect(existsSync(resolve(rootDir, xichengSeedPath))).toBe(true)

    const verifier = await readText('scripts/verify-xunjing-platform-readiness.mjs')
    const seed = await readText(xichengSeedPath)
    const moduleSql = await readText('backend/yudao/sql/mysql/xunjing-module.sql')
    const triggerEngine = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/service/app/trigger/XunjingMultimodalTriggerEngine.java'
    )
    const visionService = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/service/app/trigger/XunjingVisionRecognitionService.java'
    )
    const appService = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/service/app/XunjingAppServiceImpl.java'
    )
    const appController = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/controller/app/AppXunjingController.java'
    )
    const appServiceContract = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/service/app/XunjingAppService.java'
    )
    const interactionMapper = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/dal/mysql/event/XunjingInteractionEventMapper.java'
    )
    const appVo = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/controller/app/vo/XunjingAppVO.java'
    )
    const enums = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/enums/XunjingEnums.java'
    )
    const appTest = await readText(
      'backend/yudao/yudao-module-xunjing/src/test/java/cn/iocoder/yudao/module/xunjing/service/app/XunjingAppServiceImplTest.java'
    )
    const consoleVo = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/controller/admin/console/vo/XunjingConsoleVO.java'
    )
    const consoleController = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/controller/admin/console/XunjingConsoleController.java'
    )
    const consoleServiceContract = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/service/console/XunjingConsoleService.java'
    )
    const consoleService = await readText(
      'backend/yudao/yudao-module-xunjing/src/main/java/cn/iocoder/yudao/module/xunjing/service/console/XunjingConsoleServiceImpl.java'
    )
    const consoleTest = await readText(
      'backend/yudao/yudao-module-xunjing/src/test/java/cn/iocoder/yudao/module/xunjing/service/console/XunjingConsoleServiceImplTest.java'
    )
    const visionTest = await readText(
      'backend/yudao/yudao-module-xunjing/src/test/java/cn/iocoder/yudao/module/xunjing/service/app/trigger/XunjingVisionRecognitionServiceTest.java'
    )

    expect(verifier).toContain('xunjing-seed-xicheng-p0.sql')
    expect(verifier).toContain('xicheng-seed-data')
    expect(verifier).toContain('checkXichengPoiSeedQuality')
    expect(verifier).toContain('xicheng-poi-seed-quality')
    expect(verifier).toContain('xicheng-trigger-backend')
    expect(verifier).toContain('xicheng-ai-source-guard-backend')
    expect(verifier).toContain('xicheng-app-event-backend')
    expect(verifier).toContain('xunjing-upload-backend')
    expect(verifier).toContain('includeXichengAppCheck')
    expect(verifier).toContain('--include-xicheng-app-check')
    expect(verifier).toContain('includeXichengTriggerCheck')
    expect(verifier).toContain('--include-xicheng-trigger-check')
    expect(verifier).toContain('live-xicheng-scan-resolve')
    expect(verifier).toContain('live-xicheng-ai-chat-sourced')
    expect(verifier).toContain('live-xicheng-ai-chat-blocked')
    expect(verifier).toContain('live-xicheng-trigger-baitasi')
    expect(verifier).toContain('live-xicheng-trigger-gongwangfu')
    expect(verifier).toContain('live-xicheng-trigger-planetarium')
    expect(verifier).toContain('recordTriggerResolveEventIfPossible')
    expect(verifier).toContain('EventType.TRIGGER_RESOLVE')
    expect(verifier).toContain('ERROR_FEEDBACK("ERROR_FEEDBACK")')
    expect(verifier).toContain('AGENT_ACTION("AGENT_ACTION")')
    expect(verifier).toContain('agentActionConversionRate')
    expect(verifier).toContain('testRecordAppErrorFeedbackEventKeepsXichengContext')
    expect(verifier).toContain('testRecordAgentActionEventStoresStructuredTelemetryWithoutRawImagePayload')
    expect(verifier).toContain('testReadinessDashboardAndReportExposeAgentActionConversionMetrics')
    expect(verifier).toContain('testResolveMultimodalTriggerRecordsRecognitionEventWhenPackageProvided')
    expect(moduleSql).toContain('CREATE TABLE IF NOT EXISTS `xunjing_poi`')
    expect(triggerEngine).toContain('XunjingPoiMapper')
    expect(triggerEngine).toContain('loadDatabasePoiProfiles')
    expect(triggerEngine).toContain('selectPublishedListByRegionCode')
    expect(triggerEngine).toContain('buildSceneSignalContextText')
    expect(triggerEngine).toContain('detectSceneSignalIntent')
    expect(triggerEngine).toContain('detectAgentDecisionIntent(sceneSignals)')
    expect(triggerEngine).toContain('detectRealtimeRouteIntent(sceneSignals)')
    expect(triggerEngine).toContain('buildSceneUnderstanding')
    expect(triggerEngine).toContain('private SceneUnderstandingRespVO buildSceneUnderstanding')
    expect(triggerEngine).toContain('buildFallbackSceneFusionSummary(respVO, evidenceSignals)')
    expect(triggerEngine).toContain('buildFallbackWorldInterfaceSummary(respVO, evidenceSignals)')
    expect(triggerEngine).toContain('sceneDomainLabel(respVO.getIntent())')
    expect(triggerEngine).toContain('"start_ai_guide".equals(action) || "confirm_ai_guide".equals(action)')
    expect(triggerEngine).toContain('"开始 AI 讲解"')
    expect(triggerEngine).toContain('setSceneUnderstanding(buildSceneUnderstanding')
    expect(triggerEngine).toContain('return noMatch(regionCode, safeReqVO.getPackageCode(), safeReqVO)')
    expect(triggerEngine).toContain('respVO.setSceneUnderstanding(buildSceneUnderstanding(reqVO, List.of(), respVO))')
    expect(appVo).toContain('class SceneUnderstandingRespVO')
    expect(appVo).toContain('private SceneUnderstandingRespVO sceneUnderstanding;')
    expect(appVo).toContain('private List<String> evidenceSignals;')
    expect(appService).toContain('payload.put("sceneUnderstanding", buildTriggerSceneUnderstandingPayload(respVO))')
    expect(appService).toContain('buildTriggerSceneUnderstandingPayload')
    expect(appService).toContain('JsonNode sceneUnderstanding = root.path("sceneUnderstanding")')
    expect(appService).toContain('hydrateTriggerSceneUnderstandingText')
    expect(appService).toContain('hydrateTriggerSceneCount(reqVO, sceneUnderstanding, sceneSignals)')
    expect(appTest).toContain('testResolveMultimodalTriggerExposesSceneUnderstandingContract')
    expect(appTest).toContain('testAnswerHydratesSceneUnderstandingFromPreviousTriggerEvent')
    expect(triggerEngine).toContain('"nearbyActivitySummary"')
    expect(triggerEngine).toContain('"merchantServiceSummary"')
    expect(triggerEngine).toContain('"routeRecommendationSummary"')
    expect(triggerEngine).toContain('"menuItemNames"')
    expect(triggerEngine).toContain('"spiceLevelSummary"')
    expect(triggerEngine).toContain('"halalSuitabilityText"')
    expect(triggerEngine).toContain('"dishRecommendationSummary"')
    expect(triggerEngine).toContain('"foodItemName"')
    expect(triggerEngine).toContain('"foodOriginSummary"')
    expect(triggerEngine).toContain('"cookingMethodSummary"')
    expect(triggerEngine).toContain('"eatingMethodSummary"')
    expect(triggerEngine).toContain('"pairingSuggestionText"')
    expect(triggerEngine).toContain('"nearbyFoodRecommendationSummary"')
    expect(triggerEngine).toContain('"signOriginalText"')
    expect(triggerEngine).toContain('"signTranslationText"')
    expect(triggerEngine).toContain('"signPronunciationText"')
    expect(triggerEngine).toContain('"signNavigationHint"')
    expect(triggerEngine).toContain('"recognizedObjectName"')
    expect(triggerEngine).toContain('"eraOrPeriodText"')
    expect(triggerEngine).toContain('"structureOrCraftSummary"')
    expect(triggerEngine).toContain('"historicalStorySummary"')
    expect(triggerEngine).toContain('"hiddenDetailSummary"')
    expect(triggerEngine).toContain('"heritageItemName"')
    expect(triggerEngine).toContain('"heritageCategoryText"')
    expect(triggerEngine).toContain('"craftProcessSummary"')
    expect(triggerEngine).toContain('"performanceMethodSummary"')
    expect(triggerEngine).toContain('"soundAssetHint"')
    expect(triggerEngine).toContain('"nearbyExperienceSummary"')
    expect(triggerEngine).toContain('"plantSpeciesName"')
    expect(triggerEngine).toContain('"plantAgeEstimateText"')
    expect(triggerEngine).toContain('"plantAdaptationSummary"')
    expect(triggerEngine).toContain('"bestViewingSeasonText"')
    expect(triggerEngine).toContain('"regionalDistributionSummary"')
    expect(triggerEngine).toContain('"animalSpeciesName"')
    expect(triggerEngine).toContain('"conservationStatusText"')
    expect(triggerEngine).toContain('"habitatSummary"')
    expect(triggerEngine).toContain('"dangerAssessmentText"')
    expect(triggerEngine).toContain('"safetyReminderText"')
    expect(triggerEngine).toContain('"arDisplayHint"')
    expect(triggerEngine).toContain('"personName"')
    expect(triggerEngine).toContain('"personStorySummary"')
    expect(triggerEngine).toContain('"statueSiteReasonSummary"')
    expect(triggerEngine).toContain('"contributionSummary"')
    expect(triggerEngine).toContain('"contemporaryFigureKeywords"')
    expect(triggerEngine).toContain('"activityName"')
    expect(triggerEngine).toContain('"activityBackgroundSummary"')
    expect(triggerEngine).toContain('"performerSummary"')
    expect(triggerEngine).toContain('"scheduleTimeText"')
    expect(triggerEngine).toContain('"ticketingHint"')
    expect(triggerEngine).toContain('"venueNavigationHint"')
    expect(triggerEngine).toContain('"checkInTaskSummary"')
    expect(triggerEngine).toContain('"badgeRewardName"')
    expect(triggerEngine).toContain('"travelMapUpdateSummary"')
    expect(triggerEngine).toContain('"travelogueMaterialSummary"')
    expect(triggerEngine).toContain('"photoMomentSummary"')
    expect(triggerEngine).toContain('"socialShareDraftHint"')
    expect(triggerEngine).toContain('isOutdoorDiscomfortWeather')
    expect(triggerEngine).toContain('isNightLocalTime')
    expect(triggerEngine).toContain('case "activity" -> autoTrigger ? "open_activity_handoff" : "confirm_activity_handoff"')
    expect(triggerEngine).toContain('case "activity" -> "/pages/activity/recommend" + query')
    expect(triggerEngine).toContain('case "translate" -> autoTrigger ? "start_sign_translation" : "confirm_sign_translation"')
    expect(triggerEngine).toContain('case "translate" -> "/pages/ai-guide/detail" + query')
    expect(triggerEngine).toContain('case "safety" -> autoTrigger ? "start_safety_advisory" : "confirm_safety_advisory"')
    expect(triggerEngine).toContain('case "safety" -> "/pages/ai-guide/detail" + query')
    expect(triggerEngine).toContain('case "interpret" -> autoTrigger ? "start_scene_interpretation" : "confirm_scene_interpretation"')
    expect(triggerEngine).toContain('case "interpret" -> "/pages/ai-guide/detail" + query')
    expect(triggerEngine).toContain('case "photo" -> autoTrigger ? "start_photo_advice" : "confirm_photo_advice"')
    expect(triggerEngine).toContain('case "photo" -> "/pages/ai-guide/detail" + query')
    expect(triggerEngine).toContain('scene_context_alias')
    expect(triggerEngine).toContain('containsAny(explicitText, List.of("游记", "旅行记录", "生成游记", "打卡", "徽章"))')
    expect(visionService).toContain('recognizeImage(reqVO)')
    expect(visionService).toContain('mergeVisionSceneSignals(reqVO, recognition)')
    expect(visionService).toContain('VISION_SCENE_SIGNAL_TEXT_KEYS')
    expect(visionService).toContain('buildVisionRecognitionEvidence')
    expect(visionService).toContain('visionRecognitionStatus')
    expect(visionService).toContain('visionRecognitionModel')
    expect(visionService).toContain('visionRecognitionLabelCount')
    expect(visionService).toContain('"recognitionEvidence"')
    expect(visionService).toContain('"providerConfigured"')
    expect(visionService).toContain('"menuItemNames"')
    expect(visionService).toContain('"spiceLevelSummary"')
    expect(visionService).toContain('"halalSuitabilityText"')
    expect(visionService).toContain('"dishRecommendationSummary"')
    expect(visionService).toContain('"foodItemName"')
    expect(visionService).toContain('"foodOriginSummary"')
    expect(visionService).toContain('"cookingMethodSummary"')
    expect(visionService).toContain('"eatingMethodSummary"')
    expect(visionService).toContain('"pairingSuggestionText"')
    expect(visionService).toContain('"nearbyFoodRecommendationSummary"')
    expect(visionService).toContain('"signOriginalText"')
    expect(visionService).toContain('"signTranslationText"')
    expect(visionService).toContain('"signPronunciationText"')
    expect(visionService).toContain('"signNavigationHint"')
    expect(visionService).toContain('"recognizedObjectName"')
    expect(visionService).toContain('"eraOrPeriodText"')
    expect(visionService).toContain('"structureOrCraftSummary"')
    expect(visionService).toContain('"historicalStorySummary"')
    expect(visionService).toContain('"hiddenDetailSummary"')
    expect(visionService).toContain('"heritageItemName"')
    expect(visionService).toContain('"heritageCategoryText"')
    expect(visionService).toContain('"craftProcessSummary"')
    expect(visionService).toContain('"performanceMethodSummary"')
    expect(visionService).toContain('"soundAssetHint"')
    expect(visionService).toContain('"nearbyExperienceSummary"')
    expect(visionService).toContain('"plantSpeciesName"')
    expect(visionService).toContain('"plantAgeEstimateText"')
    expect(visionService).toContain('"plantAdaptationSummary"')
    expect(visionService).toContain('"bestViewingSeasonText"')
    expect(visionService).toContain('"regionalDistributionSummary"')
    expect(visionService).toContain('"animalSpeciesName"')
    expect(visionService).toContain('"conservationStatusText"')
    expect(visionService).toContain('"habitatSummary"')
    expect(visionService).toContain('"dangerAssessmentText"')
    expect(visionService).toContain('"safetyReminderText"')
    expect(visionService).toContain('"arDisplayHint"')
    expect(visionService).toContain('"personName"')
    expect(visionService).toContain('"personStorySummary"')
    expect(visionService).toContain('"statueSiteReasonSummary"')
    expect(visionService).toContain('"contributionSummary"')
    expect(visionService).toContain('"contemporaryFigureKeywords"')
    expect(visionService).toContain('"activityName"')
    expect(visionService).toContain('"activityBackgroundSummary"')
    expect(visionService).toContain('"performerSummary"')
    expect(visionService).toContain('"scheduleTimeText"')
    expect(visionService).toContain('"ticketingHint"')
    expect(visionService).toContain('"venueNavigationHint"')
    expect(visionService).toContain('"checkInTaskSummary"')
    expect(visionService).toContain('"badgeRewardName"')
    expect(visionService).toContain('"travelMapUpdateSummary"')
    expect(visionService).toContain('"travelogueMaterialSummary"')
    expect(visionService).toContain('"photoMomentSummary"')
    expect(visionService).toContain('"socialShareDraftHint"')
    expect(visionService).toContain('inferVisionSceneDomain(labels, caption, ocrText, sceneSignals)')
    for (const domain of [
      'architecture',
      'artifact',
      'menu',
      'food',
      'sign',
      'intangible_heritage',
      'plant',
      'animal',
      'person',
      'activity'
    ]) {
      expect(visionService).toContain(`new SceneDomainRule("${domain}"`)
    }
    expect(appService).toContain('recordTriggerResolveEventIfPossible')
    expect(appService).toContain('buildTriggerResolveEventPayload')
    expect(appService).toContain('buildTriggerMatchedSignalsPayload(respVO)')
    expect(appService).toContain('payload.put("matchedSignals", buildTriggerMatchedSignalsPayload(respVO))')
    expect(appService).toContain('payload.put("recognitionEvidence", buildTriggerRecognitionEvidencePayload(reqVO))')
    expect(appService).toContain('payload.put("sceneSnapshot", buildTriggerSceneSnapshotPayload(reqVO, respVO))')
    expect(appService).toContain('buildTriggerSceneSnapshotPayload')
    expect(appService).toContain('buildPreviousTriggerSceneSnapshotPayload(root.path("sceneSnapshot"))')
    expect(appService).toContain('payload.put("sceneSnapshot", reqVO.getVisionAgentSceneSnapshot())')
    expect(appService).toContain('buildVisionAgentSceneSnapshotContextText(reqVO.getVisionAgentSceneSnapshot())')
    expect(appService).toContain('buildTriggerRecognitionEvidencePayload')
    expect(appService).toContain('TRIGGER_SCENE_SIGNAL_TEXT_KEYS')
    expect(appService).toContain('buildTriggerSceneSignalsPayload(reqVO.getSceneSignals())')
    expect(appService).toContain('"visionRecognitionStatus"')
    expect(appService).toContain('"visionRecognitionModel"')
    expect(appTest).toContain('recognitionEvidence.get("caption").asText()')
    expect(appTest).toContain('recognitionEvidence.get("providerConfigured").asBoolean()')
    expect(appTest).toContain('sceneSnapshot.get("artifactType").asText()')
    expect(appTest).toContain('sceneSnapshot.get("serviceHandoffIntent").asText()')
    expect(appTest).toContain('visionAgentContext.get("sceneSnapshot")')
    expect(appTest).toContain('prompt.contains("识境快照=artifactType=vision_scene_snapshot")')
    expect(appService).toContain('"knowledgeGraphKeywords"')
    expect(appService).toContain('"relatedTopicKeywords"')
    expect(appService).toContain('"visitorProfileSummary"')
    expect(appService).toContain('"visitorGroup"')
    expect(appService).toContain('"interestTags"')
    expect(appService).toContain('"preferredLanguageText"')
    expect(appService).toContain('"nearbyActivitySummary"')
    expect(appService).toContain('"merchantServiceSummary"')
    expect(appService).toContain('"routeRecommendationSummary"')
    expect(appService).toContain('"menuItemNames"')
    expect(appService).toContain('"spiceLevelSummary"')
    expect(appService).toContain('"halalSuitabilityText"')
    expect(appService).toContain('"dishRecommendationSummary"')
    expect(appService).toContain('"foodItemName"')
    expect(appService).toContain('"foodOriginSummary"')
    expect(appService).toContain('"cookingMethodSummary"')
    expect(appService).toContain('"eatingMethodSummary"')
    expect(appService).toContain('"pairingSuggestionText"')
    expect(appService).toContain('"nearbyFoodRecommendationSummary"')
    expect(appService).toContain('"signOriginalText"')
    expect(appService).toContain('"signTranslationText"')
    expect(appService).toContain('"signPronunciationText"')
    expect(appService).toContain('"signNavigationHint"')
    expect(appService).toContain('"recognizedObjectName"')
    expect(appService).toContain('"eraOrPeriodText"')
    expect(appService).toContain('"structureOrCraftSummary"')
    expect(appService).toContain('"historicalStorySummary"')
    expect(appService).toContain('"hiddenDetailSummary"')
    expect(appService).toContain('"heritageItemName"')
    expect(appService).toContain('"heritageCategoryText"')
    expect(appService).toContain('"craftProcessSummary"')
    expect(appService).toContain('"performanceMethodSummary"')
    expect(appService).toContain('"soundAssetHint"')
    expect(appService).toContain('"nearbyExperienceSummary"')
    expect(appService).toContain('"plantSpeciesName"')
    expect(appService).toContain('"plantAgeEstimateText"')
    expect(appService).toContain('"plantAdaptationSummary"')
    expect(appService).toContain('"bestViewingSeasonText"')
    expect(appService).toContain('"regionalDistributionSummary"')
    expect(appService).toContain('"animalSpeciesName"')
    expect(appService).toContain('"conservationStatusText"')
    expect(appService).toContain('"habitatSummary"')
    expect(appService).toContain('"dangerAssessmentText"')
    expect(appService).toContain('"safetyReminderText"')
    expect(appService).toContain('"arDisplayHint"')
    expect(appService).toContain('"personName"')
    expect(appService).toContain('"personStorySummary"')
    expect(appService).toContain('"statueSiteReasonSummary"')
    expect(appService).toContain('"contributionSummary"')
    expect(appService).toContain('"contemporaryFigureKeywords"')
    expect(appService).toContain('"activityName"')
    expect(appService).toContain('"activityBackgroundSummary"')
    expect(appService).toContain('"performerSummary"')
    expect(appService).toContain('"scheduleTimeText"')
    expect(appService).toContain('"ticketingHint"')
    expect(appService).toContain('"venueNavigationHint"')
    expect(appService).toContain('"checkInTaskSummary"')
    expect(appService).toContain('"badgeRewardName"')
    expect(appService).toContain('"travelMapUpdateSummary"')
    expect(appService).toContain('"travelogueMaterialSummary"')
    expect(appService).toContain('"photoMomentSummary"')
    expect(appService).toContain('"socialShareDraftHint"')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "知识图谱线索", sceneSignals, "knowledgeGraphKeywords")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "关联话题", sceneSignals, "relatedTopicKeywords")')
    expect(appService).toContain('putPreviousTriggerMemoryPart(parts, "当前时间",')
    expect(appService).toContain('putPreviousTriggerMemoryPart(parts, "当前天气",')
    expect(appService).toContain('putPreviousTriggerMemoryPart(parts, "当前朝向",')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "游客画像", sceneSignals, "visitorProfileSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "同行人", sceneSignals, "visitorGroup")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "兴趣偏好", sceneSignals, "interestTags")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "偏好语言", sceneSignals, "preferredLanguageText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "附近活动", sceneSignals, "nearbyActivitySummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "商家服务", sceneSignals, "merchantServiceSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "路线建议", sceneSignals, "routeRecommendationSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "菜单菜品", sceneSignals, "menuItemNames")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "辣度", sceneSignals, "spiceLevelSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "清真信息", sceneSignals, "halalSuitabilityText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "推荐点单", sceneSignals, "dishRecommendationSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "美食名称", sceneSignals, "foodItemName")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "美食来源", sceneSignals, "foodOriginSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "制作方式", sceneSignals, "cookingMethodSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "吃法", sceneSignals, "eatingMethodSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "搭配建议", sceneSignals, "pairingSuggestionText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "附近推荐", sceneSignals, "nearbyFoodRecommendationSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "路牌原文", sceneSignals, "signOriginalText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "路牌翻译", sceneSignals, "signTranslationText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "发音", sceneSignals, "signPronunciationText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "导航提示", sceneSignals, "signNavigationHint")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "识境对象", sceneSignals, "recognizedObjectName")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "年代时期", sceneSignals, "eraOrPeriodText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "结构工艺", sceneSignals, "structureOrCraftSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "历史故事", sceneSignals, "historicalStorySummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "隐藏细节", sceneSignals, "hiddenDetailSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "非遗名称", sceneSignals, "heritageItemName")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "非遗类别", sceneSignals, "heritageCategoryText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "制作过程", sceneSignals, "craftProcessSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "演奏方式", sceneSignals, "performanceMethodSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "声音线索", sceneSignals, "soundAssetHint")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "附近体验", sceneSignals, "nearbyExperienceSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "植物名称", sceneSignals, "plantSpeciesName")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "树龄估计", sceneSignals, "plantAgeEstimateText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "耐旱原因", sceneSignals, "plantAdaptationSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "最佳观赏季", sceneSignals, "bestViewingSeasonText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "分布范围", sceneSignals, "regionalDistributionSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "动物名称", sceneSignals, "animalSpeciesName")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "保护情况", sceneSignals, "conservationStatusText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "栖息地", sceneSignals, "habitatSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "危险判断", sceneSignals, "dangerAssessmentText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "安全提醒", sceneSignals, "safetyReminderText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "AR展示", sceneSignals, "arDisplayHint")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "人物名称", sceneSignals, "personName")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "人物故事", sceneSignals, "personStorySummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "建址原因", sceneSignals, "statueSiteReasonSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "人物贡献", sceneSignals, "contributionSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "同时期人物", sceneSignals, "contemporaryFigureKeywords")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "活动名称", sceneSignals, "activityName")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "活动背景", sceneSignals, "activityBackgroundSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "演员阵容", sceneSignals, "performerSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "开始时间", sceneSignals, "scheduleTimeText")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "票务线索", sceneSignals, "ticketingHint")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "场地导航", sceneSignals, "venueNavigationHint")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "打卡任务", sceneSignals, "checkInTaskSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "徽章奖励", sceneSignals, "badgeRewardName")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "旅行地图", sceneSignals, "travelMapUpdateSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "游记素材", sceneSignals, "travelogueMaterialSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "照片时刻", sceneSignals, "photoMomentSummary")')
    expect(appService).toContain('putPreviousJsonMemoryPart(parts, "分享文案", sceneSignals, "socialShareDraftHint")')
    expect(appService).toContain('putTriggerSceneSignalNumber(payload, sceneSignals, "visionRecognitionLabelCount", false)')
    expect(appService).toContain('payload.put("serviceHandoff", buildTriggerServiceHandoffPayload(reqVO, respVO))')
    expect(appService).toContain('payload.put("agentActions", buildTriggerAgentActionsPayload(respVO))')
    expect(appService).toContain('buildTriggerAgentActionsPayload')
    expect(appService).toContain('buildTriggerAgentActionPayload(action, respVO)')
    expect(appService).toContain('payload.put("priorityRank", action.getPriorityRank())')
    expect(appService).toContain('payload.put("decisionScore", action.getDecisionScore())')
    expect(appService).toContain('payload.put("recommendationLevel", truncateForEvent(action.getRecommendationLevel(), 50))')
    expect(appService).toContain('payload.put("realSystemStatus", truncateForEvent(action.getRealSystemStatus(), 50))')
    expect(appService).toContain('payload.put("productionEvidenceText", truncateForEvent(')
    expect(appService).toContain('payload.put("poiCode", truncateForEvent(respVO.getPoiCode(), 80))')
    expect(appService).toContain('putPreviousAgentActionsMemoryPart(parts, root.get("agentActions"))')
    expect(appService).toContain('buildTriggerServiceHandoffPayload')
    expect(appService).toContain('putTriggerServiceHandoffText')
    expect(appService).toContain('hydrateMultimodalTriggerMemoryFromPreviousResolve(reqVO)')
    expect(appService).toContain('hydrateMultimodalTriggerMemoryFromPreviousAsk(resourcePackage, reqVO)')
    expect(appService).toContain('JsonNode sceneSnapshot = visionAgentContext.path("sceneSnapshot")')
    expect(appService).toContain('hydratePreviousAskSceneSnapshotSignals(sceneSignals, sceneSnapshot)')
    expect(appService).toContain('hydrateMultimodalTriggerMemoryFromPreviousAgentAction(resourcePackage, reqVO)')
    expect(appService).toContain('shouldUsePreviousAskForTriggerMemory(previousAskEvent, previousResolveEvent)')
    expect(appService).toContain('shouldUsePreviousAgentActionForTriggerMemory(previousAgentActionEvent, previousAskEvent, previousResolveEvent)')
    expect(appService).toContain('buildContinuousAgentActionSceneFusionSummary(agentAction)')
    expect(appService).toContain('triggerRequiresRealSystem(action, intent)')
    expect(appService).toContain('"activity".equals(intent)')
    expect(appService).toContain('"活动票务"')
    expect(appService).toContain('"translate".equals(intent)')
    expect(appService).toContain('"路牌翻译"')
    expect(appService).toContain('"safety".equals(intent)')
    expect(appService).toContain('"安全提醒"')
    expect(appService).toContain('"interpret".equals(intent)')
    expect(appService).toContain('"深度识境"')
    expect(appService).toContain('"photo".equals(intent)')
    expect(appService).toContain('"拍照建议"')
    expect(appService).toContain('hasFreshMultimodalTriggerSignal(reqVO)')
    expect(appTest).toContain('testResolveMultimodalTriggerHydratesSceneSnapshotFromPreviousAskEvent')
    expect(appTest).toContain('sceneSignals.get("visionRecognitionStatus").asText()')
    expect(appService).not.toContain('payload.put("sceneSignals", reqVO.getSceneSignals())')
    expect(appService).not.toContain('payload.put("candidates", respVO.getCandidates())')
    expect(appService).toContain('EventType.TRIGGER_RESOLVE')
    expect(appService).toContain('EventType.AGENT_ACTION')
    expect(appService).toContain('buildAgentActionEventPayload')
    expect(appService).toContain('sanitizeAgentActionClientPayload')
    expect(appService).toContain('Map<String, Object> agentAction = buildAgentActionEventPayload(clientPayloadObject)')
    expect(appService).toContain('payload.put("agentAction", agentAction)')
    expect(appService).toContain('payload.put("travelRecordMaterial", travelRecordMaterial)')
    expect(appService).toContain('buildAgentActionTravelRecordMaterialPayload(')
    expect(appService).toContain('Map<String, Object> sourceSceneSnapshot = buildAgentActionSourceSceneSnapshotPayload(resourcePackage, reqVO)')
    expect(appService).toContain('agentAction.put("sourceSceneSnapshot", sourceSceneSnapshot)')
    expect(appService).toContain('payload.put("sourceSceneSnapshot", sourceSceneSnapshot)')
    expect(appService).toContain('resourcePackage, reqVO, agentAction, sourceSceneSnapshot')
    expect(appService).toContain('putTriggerSceneSnapshotText(payload, "photoTakenAt"')
    expect(appService).toContain('payload.put("photoExifLocation", photoExifLocation)')
    expect(appService).toContain('payload.put("photoTakenAt", sourceSceneSnapshot.get("photoTakenAt"))')
    expect(appService).toContain('payload.put("photoExifLocation", sourceSceneSnapshot.get("photoExifLocation"))')
    expect(appService).toContain('hydrateVisionAgentContextFromPreviousAgentAction(resourcePackage, reqVO, explicitChatTargetContext)')
    expect(appService).toContain('shouldUsePreviousAgentActionForChatContext(previousAgentActionEvent, previousAskEvent, previousTriggerEvent)')
    expect(appService).toContain('hasExplicitChatTargetContext(reqVO)')
    expect(appService).toContain('EventType.AGENT_ACTION.getType()')
    expect(appService).toContain('JsonNode agentAction = root.path("agentAction")')
    expect(appService).toContain('buildAgentActionServiceHandoffSummary(agentAction)')
    expect(appService).toContain('buildTravelRecordMaterialFeed(resourcePackage, userTraceId, limit)')
    expect(appService).toContain('buildTravelRecordMaterialItem(event)')
    expect(appService).toContain('root.path("travelRecordMaterial")')
    expect(appService).toContain('normalizeTravelRecordMaterialLimit(limit)')
    expect(appService).toContain('buildVisionAgentMemorySession(resourcePackage, userTraceId, limit)')
    expect(appService).toContain('buildVisionAgentMemorySceneItem(event)')
    expect(appService).toContain('selectListByPackageIdAndUserTraceIdAndEventTypes')
    expect(appService).toContain('EventType.TRIGGER_RESOLVE.getType()')
    expect(appService).toContain('EventType.ASK.getType()')
    expect(appService).toContain('buildVisionAgentMemoryPoiTrailText')
    expect(appService).toContain('buildVisionAgentMemoryContinuityCueText')
    expect(appService).toContain('buildVisionAgentServiceHandoffTaskFeed(resourcePackage, userTraceId, limit)')
    expect(appService).toContain('buildVisionAgentServiceHandoffTaskItem(event)')
    expect(appService).toContain('resolveServiceHandoffRealSystemStatus')
    expect(appService).toContain('SERVICE_HANDOFF_REAL_SYSTEM_BOUNDARY_TEXT')
    expect(appService).toContain('buildVisionAgentSceneContext(resourcePackage, userTraceId, regionCode, poiCode, limit)')
    expect(appService).toContain('resolveSceneContextLatestScene')
    expect(appService).toContain('resolveSceneContextKnowledgeGraph')
    expect(appService).toContain('buildSceneContextReady')
    expect(appService).toContain('visionRecognitionService.getProviderStatus()')
    expect(appService).toContain('buildVisionAgentKnowledgeGraph(resourcePackage, regionCode, poiCode, limit)')
    expect(appService).toContain('buildKnowledgeGraphAnchorNode')
    expect(appService).toContain('buildKnowledgeGraphRelatedPoiNodes')
    expect(appService).toContain('buildKnowledgeGraphTopicNodes')
    expect(appService).toContain('buildKnowledgeGraphEdges')
    expect(appService).toContain('buildKnowledgeGraphSources')
    expect(appService).toContain('extractKnowledgeGraphRecommendedQuestions')
    expect(appController).toContain('@GetMapping("/travel-record/materials")')
    expect(appController).toContain('appService.listTravelRecordMaterials(packageCode, userTraceId, limit)')
    expect(appController).toContain('@GetMapping("/memory/session")')
    expect(appController).toContain('appService.getVisionAgentMemorySession(packageCode, userTraceId, limit)')
    expect(appController).toContain('@GetMapping("/service-handoff/tasks")')
    expect(appController).toContain('appService.listVisionAgentServiceHandoffTasks(packageCode, userTraceId, limit)')
    expect(appController).toContain('@GetMapping("/scene/context")')
    expect(appController).toContain('appService.getVisionAgentSceneContext(packageCode, userTraceId, regionCode, poiCode, limit)')
    expect(appController).toContain('@GetMapping("/vision/provider/status")')
    expect(appController).toContain('appService.getVisionProviderStatus()')
    expect(appController).toContain('@GetMapping("/knowledge/graph")')
    expect(appController).toContain('appService.getVisionAgentKnowledgeGraph(packageCode, regionCode, poiCode, limit)')
    expect(appVo).toContain('class TravelRecordMaterialFeedRespVO')
    expect(appVo).toContain('class TravelRecordMaterialRespVO')
    expect(appVo).toContain('private Map<String, Object> sourceSceneSnapshot;')
    expect(appVo).toContain('class VisionAgentMemorySessionRespVO')
    expect(appVo).toContain('class VisionAgentMemorySceneRespVO')
    expect(appVo).toContain('private String continuityCueText;')
    expect(appVo).toContain('private Map<String, Object> sceneSnapshot;')
    expect(appVo).toContain('class VisionAgentServiceHandoffTaskFeedRespVO')
    expect(appVo).toContain('private Long realSystemRequiredTaskCount;')
    expect(appVo).toContain('private String realSystemBoundaryText;')
    expect(appVo).toContain('class VisionAgentServiceHandoffTaskRespVO')
    expect(appVo).toContain('private String realSystemStatus;')
    expect(appVo).toContain('private String handoffSummary;')
    expect(appVo).toContain('class VisionAgentSceneContextRespVO')
    expect(appVo).toContain('private Boolean contextReady;')
    expect(appVo).toContain('private Long latestEventId;')
    expect(appVo).toContain('private Boolean knowledgeGraphAvailable;')
    expect(appVo).toContain('private VisionAgentMemorySessionRespVO memorySession;')
    expect(appVo).toContain('private VisionAgentServiceHandoffTaskFeedRespVO serviceHandoff;')
    expect(appVo).toContain('private VisionAgentKnowledgeGraphRespVO knowledgeGraph;')
    expect(appVo).toContain('class VisionProviderStatusRespVO')
    expect(appVo).toContain('private Boolean providerConfigured;')
    expect(appVo).toContain('private String apiKeyFingerprint;')
    expect(appVo).toContain('private List<String> missingConfigKeys;')
    expect(appVo).toContain('private String productionEvidenceText;')
    expect(appVo).toContain('class VisionAgentKnowledgeGraphRespVO')
    expect(appVo).toContain('class VisionAgentKnowledgeGraphNodeRespVO')
    expect(appVo).toContain('class VisionAgentKnowledgeGraphEdgeRespVO')
    expect(appVo).toContain('private List<SourceRespVO> sources;')
    expect(appServiceContract).toContain('TravelRecordMaterialFeedRespVO listTravelRecordMaterials(String packageCode, String userTraceId, Integer limit)')
    expect(appServiceContract).toContain('VisionAgentMemorySessionRespVO getVisionAgentMemorySession(String packageCode, String userTraceId, Integer limit)')
    expect(appServiceContract).toContain('VisionAgentServiceHandoffTaskFeedRespVO listVisionAgentServiceHandoffTasks(String packageCode, String userTraceId, Integer limit)')
    expect(appServiceContract).toContain('VisionAgentSceneContextRespVO getVisionAgentSceneContext(String packageCode, String userTraceId, String regionCode, String poiCode, Integer limit)')
    expect(appServiceContract).toContain('VisionProviderStatusRespVO getVisionProviderStatus()')
    expect(appServiceContract).toContain('VisionAgentKnowledgeGraphRespVO getVisionAgentKnowledgeGraph(String packageCode, String regionCode, String poiCode, Integer limit)')
    expect(visionService).toContain('VisionProviderStatusRespVO getProviderStatus()')
    expect(visionService).toContain('fingerprintSecret')
    expect(visionService).toContain('missingConfigKeys')
    expect(interactionMapper).toContain('selectListByPackageIdAndUserTraceIdAndEventType')
    expect(interactionMapper).toContain('selectListByPackageIdAndUserTraceIdAndEventTypes')
    expect(interactionMapper).toContain('orderByAsc(XunjingInteractionEventDO::getId)')
    expect(consoleController).toContain('@PostMapping(value = "/knowledge-documents/upload"')
    expect(consoleController).toContain('@PostMapping(value = "/media-assets/upload"')
    expect(consoleController).toContain('MediaType.MULTIPART_FORM_DATA_VALUE')
    expect(consoleVo).toContain('class KnowledgeDocumentUploadReqVO')
    expect(consoleVo).toContain('class MediaAssetUploadReqVO')
    expect(consoleVo).toContain('private MultipartFile file;')
    expect(consoleServiceContract).toContain('Long uploadKnowledgeDocument(KnowledgeDocumentUploadReqVO reqVO);')
    expect(consoleServiceContract).toContain('Long uploadMediaAsset(MediaAssetUploadReqVO reqVO);')
    expect(consoleService).toContain('private FileApi fileApi;')
    expect(consoleService).toContain('requireFileApi().createFile(content, fileName, directory, file.getContentType())')
    expect(consoleService).toContain('uploadDirectory("xunjing/tourism-knowledge", reqVO.getPackageId())')
    expect(consoleService).toContain('uploadDirectory("xunjing/tourism-media", reqVO.getPackageId())')
    expect(consoleService).toContain('buildKnowledgeUploadDigest(file, content)')
    expect(consoleService).toContain('defaultKnowledgeVectorStatusForReview(reqVO, document)')
    expect(consoleTest).toContain('testUploadKnowledgeDocumentStoresFileAndCreatesPendingTourismDocument')
    expect(consoleTest).toContain('testReviewUploadedKnowledgeDocumentDefaultsIndexedWhenApproved')
    expect(consoleTest).toContain('testUploadMediaAssetStoresFileAndCreatesPendingImageMaterial')
    expect(consoleTest).toContain('fileApi.createFile')
    expect(appService).toContain('resolveAppEventQrCode(reqVO, hasText(reqVO.getPackageCode()))')
    expect(appService).not.toContain('payload.put("imageBase64"')
    expect(appVo).toContain('private List<MultimodalAgentActionRespVO> agentActions;')
    expect(appVo).toContain('class MultimodalAgentActionRespVO')
    expect(appVo).toContain('private Integer priorityRank;')
    expect(appVo).toContain('private Double decisionScore;')
    expect(appVo).toContain('private String recommendationLevel;')
    expect(appVo).toContain('private String realSystemStatus;')
    expect(appVo).toContain('private String productionEvidenceText;')
    expect(appVo).toContain('private Map<String, Object> sceneSignals;')
    expect(triggerEngine).toContain('respVO.setAgentActions(buildAgentActions(')
    expect(triggerEngine).toContain('buildCoreAgentActionPack(actions, regionCode, poiCode, packageCode)')
    expect(triggerEngine).toContain('rankAgentActions(actions, primaryAction, intent, sceneSignals)')
    expect(triggerEngine).toContain('applyAgentActionDecisionMetadata(action, rank, primaryAction, intent, sceneSignals)')
    expect(triggerEngine).toContain('calculateAgentActionDecisionScore(')
    expect(triggerEngine).toContain('resolveAgentActionRecommendationLevel(')
    expect(triggerEngine).toContain('resolveAgentActionRealSystemStatus(')
    expect(triggerEngine).toContain('buildAgentActionProductionEvidenceText(')
    expect(triggerEngine).toContain('"handoff_required"')
    expect(triggerEngine).toContain('"ready_for_local_state"')
    expect(triggerEngine).toContain('"complete_check_in"')
    expect(triggerEngine).toContain('"claim_badge"')
    expect(triggerEngine).toContain('"add_to_travel_map"')
    expect(triggerEngine).toContain('"generate_travelogue"')
    expect(triggerEngine).toContain('"nearby_food"')
    expect(triggerEngine).toContain('"activity_ticketing"')
    expect(enums).toContain('TRIGGER_RESOLVE("TRIGGER_RESOLVE")')
    expect(enums).toContain('ERROR_FEEDBACK("ERROR_FEEDBACK")')
    expect(enums).toContain('AGENT_ACTION("AGENT_ACTION")')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesPublishedPoiFromDatabase')
    expect(appTest).toContain('testResolveMultimodalTriggerBuildsCoreAgentActionPackForRecognizedPoi')
    expect(appTest).toContain('testResolveMultimodalTriggerRanksAgentActionDecisionQueue')
    expect(appTest).toContain('testRecordAgentActionEventStoresStructuredTelemetryWithoutRawImagePayload')
    expect(appTest).toContain('testRecordAgentActionEventBindsLatestVisionSceneSnapshotToTravelRecordMaterial')
    expect(appTest).toContain('testTravelRecordMaterialCarriesPhotoTimeExifLocationAndRecognizedPoi')
    expect(appTest).toContain('testListTravelRecordMaterialsReturnsSceneSnapshotPhotoAndPoiTimeline')
    expect(appTest).toContain('testGetVisionAgentMemorySessionBuildsContinuousSceneTimeline')
    expect(appTest).toContain('testGetVisionAgentKnowledgeGraphBuildsSourceBackedPoiTopicNetwork')
    expect(appTest).toContain('testListVisionAgentServiceHandoffTasksExposesRealSystemBoundary')
    expect(appTest).toContain('testGetVisionAgentSceneContextBuildsSceneEngineContextPacket')
    expect(appTest).toContain('getKnowledgeGraphAvailable()')
    expect(appTest).toContain('getServiceHandoffTaskCount()')
    expect(visionTest).toContain('testGetProviderStatusReportsMissingConfigWithoutLeakingSecrets')
    expect(visionTest).toContain('testGetProviderStatusReportsConfiguredFingerprintOnly')
    expect(appTest).toContain('getRealSystemRequiredTaskCount()')
    expect(appTest).toContain('getRealSystemStatus()')
    expect(appTest).toContain('travelRecordMaterial.get("sourceSceneSnapshot")')
    expect(appTest).toContain('travelRecordMaterial.get("photoTakenAt")')
    expect(appTest).toContain('travelRecordMaterial.get("photoExifLocation")')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesSceneSignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesOperationSignalsForContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesMenuSignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesFoodSignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesSignTranslationSignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesInterpretationSignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesHeritageSignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesPlantSignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesAnimalSignalsForSafetyIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesPersonSignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesActivitySignalsForIntentAndContextMatch')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesTravelRecordSignalsForIntentAndContextMatch')
    expect(appTest).toContain('travelRecordMaterial.get("generateTravelogue").asBoolean()')
    expect(appTest).toContain('assertTrue(agentActions.toString().contains("\\"poiCode\\":\\"xicheng-gongwangfu\\""))')
    expect(appTest).toContain('complete_check_in')
    expect(appTest).toContain('add_to_travel_map')
    expect(appTest).toContain('generate_travelogue')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesPhotoAdviceIntent')
    expect(appTest).toContain('testResolveMultimodalTriggerRecordsRecognitionEventWhenPackageProvided')
    expect(appTest).toContain('testResolveMultimodalTriggerBuildsFallbackSceneUnderstandingWithoutClientSignals')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesVisionProviderOcrWhenClientOnlySendsPhoto')
    expect(appTest).toContain('testResolveMultimodalTriggerNoMatchKeepsVisionEvidenceInSceneUnderstanding')
    expect(appTest).toContain('testResolveMultimodalTriggerRecordsServiceHandoffContractForMerchantScene')
    expect(appTest).toContain('testResolveMultimodalTriggerRecordsSceneSignalsWithoutRawRecognitionContext')
    expect(appTest).toContain('testResolveMultimodalTriggerHydratesContinuousContextFromPreviousTriggerEvent')
    expect(appTest).toContain('testResolveMultimodalTriggerDoesNotReusePreviousSceneIntentWhenFreshOcrExists')
    expect(appTest).toContain('testResolveMultimodalTriggerHydratesContinuousContextFromPreviousAskEvent')
    expect(appTest).toContain('testResolveMultimodalTriggerHydratesExecutedAgentActionIntoContinuousContext')
    expect(appTest).toContain('testResolveMultimodalTriggerUsesLatestAskWhenItIsNewerThanPreviousTrigger')
    expect(appTest).toContain('testAnswerHydratesExecutedAgentActionFromPreviousAgentActionEvent')
    expect(appTest).toContain('testAnswerDoesNotLetOlderAgentActionOverrideNewerTriggerContext')
    expect(appTest).toContain('testAnswerKeepsExplicitPoiContextAheadOfPreviousTriggerAndAgentAction')
    expect(appTest).toContain('testAnswerUsesKnowledgeGraphSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesVisitorProfileSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesRealtimeEnvironmentSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesOperationSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesMenuSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesFoodSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesSignTranslationSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesInterpretationSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesHeritageSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesPlantSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesAnimalSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesPersonSignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesActivitySignalsFromPreviousTriggerForSourceSearch')
    expect(appTest).toContain('testAnswerUsesTravelRecordSignalsFromPreviousTriggerForSourceSearch')
    expect(consoleVo).toContain('private Long triggerResolveCount;')
    expect(consoleVo).toContain('private Long agentActionCount;')
    expect(consoleVo).toContain('private BigDecimal agentActionConversionRate;')
    expect(consoleVo).toContain('private Long totalTriggerResolveCount;')
    expect(consoleVo).toContain('private Long totalAgentActionCount;')
    expect(consoleVo).toContain('class AgentActionMetricRespVO')
    expect(consoleVo).toContain('private List<AgentActionMetricRespVO> topAgentActions;')
    expect(consoleVo).toContain('class AgentActionPoiFunnelRespVO')
    expect(consoleVo).toContain('private List<AgentActionPoiFunnelRespVO> agentActionPoiFunnels;')
    expect(consoleVo).toContain('private BigDecimal conversionRate;')
    expect(consoleVo).toContain('class AgentActionTimeWindowRespVO')
    expect(consoleVo).toContain('private List<AgentActionTimeWindowRespVO> agentActionTimeWindows;')
    expect(consoleVo).toContain('private String windowKey;')
    expect(consoleVo).toContain('private String windowLabel;')
    expect(consoleVo).toContain('private Long executionCount;')
    expect(consoleVo).toContain('private BigDecimal shareRate;')
    expect(consoleService).toContain('calculateAgentActionConversionRate')
    expect(consoleService).toContain('buildTopAgentActionMetrics')
    expect(consoleService).toContain('buildAgentActionPoiFunnels')
    expect(consoleService).toContain('buildAgentActionTimeWindows')
    expect(consoleService).toContain('agentActionWindow')
    expect(consoleService).toContain('eventInWindow')
    expect(consoleService).toContain('recordPoiFunnelTriggerResolve')
    expect(consoleService).toContain('recordPoiFunnelAgentAction')
    expect(consoleService).toContain('selectListByPackageIdsAndEventType')
    expect(consoleService).toContain('agentActionText')
    expect(consoleService).toContain('EventType.TRIGGER_RESOLVE.getType()')
    expect(consoleService).toContain('EventType.AGENT_ACTION.getType()')
    expect(consoleService).toContain('\\"agentActionConversionRate\\":')
    expect(consoleTest).toContain('testReadinessDashboardAndReportExposeAgentActionConversionMetrics')
    expect(consoleTest).toContain('testDashboardRanksAgentActionExecutionsByActionIntentAndPoi')
    expect(consoleTest).toContain('testDashboardBuildsPoiAgentActionFunnelFromTriggerAndActionEvents')
    expect(consoleTest).toContain('testDashboardBuildsAgentActionTimeWindowFunnels')
    expect(consoleTest).toContain('new BigDecimal("0.5000")')
    expect(consoleTest).toContain('new BigDecimal("0.6667")')
    expect(consoleTest).toContain('new BigDecimal("1.0000")')
    expect(consoleTest).toContain('"last30d"')
    expect(visionTest).toContain('testEnrichMergesFoodSceneSignalsFromVisionProvider')
    expect(visionTest).toContain('testEnrichMergesHeritageSceneSignalsFromVisionProvider')
    expect(visionTest).toContain('testEnrichMergesInterpretationSceneSignalsFromVisionProvider')
    expect(visionTest).toContain('testEnrichMergesPlantSceneSignalsFromVisionProvider')
    expect(visionTest).toContain('testEnrichMergesAnimalSceneSignalsFromVisionProvider')
    expect(visionTest).toContain('testEnrichMergesPersonSceneSignalsFromVisionProvider')
    expect(visionTest).toContain('testEnrichMergesActivitySceneSignalsFromVisionProvider')
    expect(visionTest).toContain('testEnrichMergesTravelRecordSceneSignalsFromVisionProvider')
    expect(appTest).toContain('testAnswerHydratesPhotoAdviceHandoffFromTrigger')
    expect(appTest).toContain('testAnswerMarksMerchantTriggerHandoffAsRealSystemRequired')
    expect(appTest).toContain('testRecordAppErrorFeedbackEventKeepsXichengContext')
    expect(appTest).toContain('testAnswerBlocksWhenReviewedSourcesDoNotMatchXichengPoiContext')

    for (const snippet of [
      'XICHENG-2026-P0',
      'XICHENG-MAP-001',
      'QR-XICHENG-MAP-001',
      'beijing-xicheng',
      '"regionCode":"beijing-xicheng"',
      '"reviewStatus":"APPROVED"',
      '"geoStatus":"REVIEW_REQUIRED"',
      '"licenseStatus":"REVIEW_REQUIRED"',
      '"poiId":"xicheng-baitasi"',
      '"poiId":"xicheng-emperors-temple"',
      '"poiId":"xicheng-beihai-park"',
      '"poiId":"xicheng-shichahai"',
      '"poiId":"xicheng-dashilar"',
      '西城区文物保护单位（81处）',
      'https://www.bjxch.gov.cn/xcfw/whfw/xxxq/pnidpv736523.html',
      '妙应寺白塔',
      '历代帝王庙',
      '北海公园',
      '西城 AI 旅伴 P0 固定评测集'
    ]) {
      expect(seed).toContain(snippet)
    }

    const poiRows = xichengPoiSeedRows(seed)
    expect(poiRows).toHaveLength(80)
    expect(seed.match(/"poiId":"xicheng-/g) ?? []).toHaveLength(80)
    for (const row of poiRows) {
      const poiCode = row.match(/'(?<poiCode>xicheng-[^']+)'/)?.groups?.poiCode
      expect(poiCode).toBeTruthy()
      expect(row).toContain("'beijing-xicheng'")
      expect(row).toContain("'P0'")
      expect(row).toContain("'GCJ02'")
      expect(row).toMatch(/'sourceUrl',@xicheng_[a-z0-9_]*source_url/)
      expect(row).toContain('"gpsRadiusMeters":')
      expect(row).toContain('"ocrKeywords":[')
      expect(row).toContain('"photoLabels":[')
      expect(row).toContain(`"poiId":"${poiCode}"`)
      expect(row).toContain('"shortIntro":"')
      expect(row).toContain('"recommendedQuestions":[')
      expect(row).toContain("'APPROVED', 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 'PUBLISHED'")
      const heritageNumber = poiCode.match(/^xicheng-heritage-(\d{3})-/)?.[1]
      if (heritageNumber) {
        expect(row).toContain(`'heritageNo',${Number.parseInt(heritageNumber, 10)}`)
      }
    }
    expect(seed).toContain('INSERT INTO `xunjing_poi`')
    expect(seed).toContain('INSERT INTO `xunjing_knowledge_document`')
    expect(seed).toContain("CONCAT(`name`, ' POI 级已审核来源')")
    expect(seed).toContain('xicheng-baitasi')
    expect(seed).toContain('@xicheng_baitasi_source_url')
    expect(seed).toContain('@xicheng_emperors_temple_source_url')
    expect(seed).toContain('@xicheng_shichahai_source_url')
    expect(seed).toContain('@xicheng_gongwangfu_source_url')
    expect(seed).toContain('@xicheng_niujie_source_url')
    expect(seed).toContain('@xicheng_financial_street_source_url')
    for (const row of poiRows.slice(0, 24)) {
      expect(row).not.toContain("'sourceUrl',@xicheng_source_url")
    }
    expect(seed).toContain('POI 级已审核来源')
    expect(seed).toContain("JSON_UNQUOTE(JSON_EXTRACT(`content_json`, '$.shortIntro'))")
    expect(seed).toContain("CONCAT(@xicheng_source_url, _utf8mb4'#%')")
    expect(seed).toContain('INSERT INTO `xunjing_ai_eval_case`')
    expect(seed).toContain('@xicheng_source_url COLLATE utf8mb4_unicode_ci')
  })
})
